package com.hibernate.dto;

// Generated 03-Nov-2014 17:39:00 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Audiostream generated by hbm2java
 */
@Entity
@Table(name = "audiostream", catalog = "italk2learn")
public class Audiostream implements java.io.Serializable {

	private Integer idAudiostream;
	private User user;
	private byte[] bytearray;
	private Date date;

	public Audiostream() {
	}

	public Audiostream(User user, byte[] bytearray, Date date) {
		this.user = user;
		this.bytearray = bytearray;
		this.date = date;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_audiostream", unique = true, nullable = false)
	public Integer getIdAudiostream() {
		return this.idAudiostream;
	}

	public void setIdAudiostream(Integer idAudiostream) {
		this.idAudiostream = idAudiostream;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_user", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "bytearray", nullable = false)
	public byte[] getBytearray() {
		return this.bytearray;
	}

	public void setBytearray(byte[] bytearray) {
		this.bytearray = bytearray;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", nullable = false, length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
