package com.hibernate.dto;

// Generated 12-May-2015 16:08:13 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Exercisequiz generated by hbm2java
 */
@Entity
@Table(name = "exercisequiz", catalog = "italk2learn")
public class Exercisequiz implements java.io.Serializable {

	private Integer idExercisequiz;
	private User user;
	private String jsonval;
	private String exView;
	private String exName;
	private Date date;
	private int typeQuiz;

	public Exercisequiz() {
	}

	public Exercisequiz(User user, Date date, int typeQuiz) {
		this.user = user;
		this.date = date;
		this.typeQuiz = typeQuiz;
	}

	public Exercisequiz(User user, String jsonval, String exView,
			String exName, Date date, int typeQuiz) {
		this.user = user;
		this.jsonval = jsonval;
		this.exView = exView;
		this.exName = exName;
		this.date = date;
		this.typeQuiz = typeQuiz;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_exercisequiz", unique = true, nullable = false)
	public Integer getIdExercisequiz() {
		return this.idExercisequiz;
	}

	public void setIdExercisequiz(Integer idExercisequiz) {
		this.idExercisequiz = idExercisequiz;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_user", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "jsonval", length = 500)
	public String getJsonval() {
		return this.jsonval;
	}

	public void setJsonval(String jsonval) {
		this.jsonval = jsonval;
	}

	@Column(name = "exView", length = 50)
	public String getExView() {
		return this.exView;
	}

	public void setExView(String exView) {
		this.exView = exView;
	}

	@Column(name = "exName", length = 50)
	public String getExName() {
		return this.exName;
	}

	public void setExName(String exName) {
		this.exName = exName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", nullable = false, length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "typeQuiz", nullable = false)
	public int getTypeQuiz() {
		return this.typeQuiz;
	}

	public void setTypeQuiz(int typeQuiz) {
		this.typeQuiz = typeQuiz;
	}

}
