package com.hibernate.dto;

// Generated 14-Jul-2014 17:03:14 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Flexercise generated by hbm2java
 */
@Entity
@Table(name = "flexercise", catalog = "italk2learn")
public class Flexercise implements java.io.Serializable {

	private Integer idFltask;
	private Exercises exercises;
	private User user;
	private String event;
	private Date date;

	public Flexercise() {
	}

	public Flexercise(Exercises exercises, User user, Date date) {
		this.exercises = exercises;
		this.user = user;
		this.date = date;
	}

	public Flexercise(Exercises exercises, User user, String event, Date date) {
		this.exercises = exercises;
		this.user = user;
		this.event = event;
		this.date = date;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_fltask", unique = true, nullable = false)
	public Integer getIdFltask() {
		return this.idFltask;
	}

	public void setIdFltask(Integer idFltask) {
		this.idFltask = idFltask;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_exercise", nullable = false)
	public Exercises getExercises() {
		return this.exercises;
	}

	public void setExercises(Exercises exercises) {
		this.exercises = exercises;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_user", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "event", length = 1000)
	public String getEvent() {
		return this.event;
	}

	public void setEvent(String event) {
		this.event = event;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", nullable = false, length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
