package com.hibernate.dto;

// Generated 08-Nov-2013 17:48:29 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Sequence generated by hbm2java
 */
@Entity
@Table(name = "sequence", catalog = "italk2learn")
public class Sequence implements java.io.Serializable {

	private Integer idSequence;
	private Exercises exercises;
	private User user;
	private Integer idNextexercise;
	private String feedback;

	public Sequence() {
	}

	public Sequence(Exercises exercises, User user, Integer idNextexercise,
			String feedback) {
		this.exercises = exercises;
		this.user = user;
		this.idNextexercise = idNextexercise;
		this.feedback = feedback;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_sequence", unique = true, nullable = false)
	public Integer getIdSequence() {
		return this.idSequence;
	}

	public void setIdSequence(Integer idSequence) {
		this.idSequence = idSequence;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_exercise")
	public Exercises getExercises() {
		return this.exercises;
	}

	public void setExercises(Exercises exercises) {
		this.exercises = exercises;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_user")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "id_nextexercise")
	public Integer getIdNextexercise() {
		return this.idNextexercise;
	}

	public void setIdNextexercise(Integer idNextexercise) {
		this.idNextexercise = idNextexercise;
	}

	@Column(name = "feedback", length = 500)
	public String getFeedback() {
		return this.feedback;
	}

	public void setFeedback(String feedback) {
		this.feedback = feedback;
	}

}
