package com.hibernate.dto;

// Generated 15-May-2015 13:12:29 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Snalog generated by hbm2java
 */
@Entity
@Table(name = "snalog", catalog = "italk2learn")
public class Snalog implements java.io.Serializable {

	private Integer idSnalog;
	private User user;
	private String snakey;
	private String snavalue;
	private Date date;

	public Snalog() {
	}

	public Snalog(User user, Date date) {
		this.user = user;
		this.date = date;
	}

	public Snalog(User user, String snakey, String snavalue, Date date) {
		this.user = user;
		this.snakey = snakey;
		this.snavalue = snavalue;
		this.date = date;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_snalog", unique = true, nullable = false)
	public Integer getIdSnalog() {
		return this.idSnalog;
	}

	public void setIdSnalog(Integer idSnalog) {
		this.idSnalog = idSnalog;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_user", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "snakey", length = 50)
	public String getSnakey() {
		return this.snakey;
	}

	public void setSnakey(String snakey) {
		this.snakey = snakey;
	}

	@Column(name = "snavalue", length = 1000)
	public String getSnavalue() {
		return this.snavalue;
	}

	public void setSnavalue(String snavalue) {
		this.snavalue = snavalue;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", nullable = false, length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
