package com.hibernate.dto;

// Generated 08-Mar-2013 17:55:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Userdetails generated by hbm2java
 */
@Entity
@Table(name = "userdetails", catalog = "italk2learn")
public class Userdetails implements java.io.Serializable {

	private Integer password;
	private String user;
	private String name;
	private String email;
	private String phone;
	private String website;
	private String message;

	public Userdetails() {
	}

	public Userdetails(String user) {
		this.user = user;
	}

	public Userdetails(String user, String name, String email, String phone,
			String website, String message) {
		this.user = user;
		this.name = name;
		this.email = email;
		this.phone = phone;
		this.website = website;
		this.message = message;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "password", unique = true, nullable = false)
	public Integer getPassword() {
		return this.password;
	}

	public void setPassword(Integer password) {
		this.password = password;
	}

	@Column(name = "user", nullable = false, length = 20)
	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	@Column(name = "name", length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "email", length = 200)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "phone", length = 20)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "website", length = 200)
	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	@Column(name = "message", length = 200)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

}
