(function (lib, img, cjs, whizz) {

	var p; // shortcut to reference prototypes



	(lib.blueBox = function() {
		this.initialize();

		// Layer 1
		this.shape_2 = new cjs.Shape();
		this.shape_2.graphics.f("#00CCFF").s().p("AjBiXIGDAAIAAEvImDAAIAAkv").cp();
		this.shape_2.setTransform(19.4,15.2);

		this.addChild(this.shape_2);
	}).prototype = p = new cjs.Container();
	p.nominalBounds = new cjs.Rectangle(0,0,38.8,30.4);

	(lib.whiteBox = function() {
		this.initialize();

		// Layer 1
		this.shape = new cjs.Shape();
		this.shape.graphics.f("#FFFFFF").s().p("AjBCYIAAkvIGDAAIAAEvImDAA").cp();
		this.shape.setTransform(19.4,15.2);

		this.addChild(this.shape);
	}).prototype = p = new cjs.Container();
	p.nominalBounds = new cjs.Rectangle(0,0,38.8,30.4);


	(lib.redBox = function() {
		this.initialize();

		// Layer 1
		this.shape_1 = new cjs.Shape();
		this.shape_1.graphics.f("#FF0000").s().p("AjBiXIGDAAIAAEvImDAAIAAkv").cp();
		this.shape_1.setTransform(19.4,15.2);

		this.addChild(this.shape_1);
	}).prototype = p = new cjs.Container();
	p.nominalBounds = new cjs.Rectangle(0,0,38.8,30.4);

	(lib.Back = function(mode,startPosition,loop) {
		this.initialize(mode,startPosition,loop,{static:0,wrong:1,wrong2:23,correct:58},true);

		// timeline functions:
		this.frame_0 = function() {
			this.stop();
		}
		this.frame_12 = function() {
			if(this === this.parent.back0){this.parent.answer0.setValue();}
			else if (this === this.parent.back1){this.parent.answer1.setValue();}
			else if (this === this.parent.back2){this.parent.answer2.setValue();}
			else if (this === this.parent.back3){this.parent.answer3.setValue();}
			else if (this === this.parent.back4){this.parent.answer4.setValue();}
			else if (this === this.parent.back5){this.parent.answer5.setValue();}
		}
		this.frame_22 = function() {
			this.stop();
		}
		this.frame_52 = function() {
			if(this === this.parent.back0){
				// Top Row, Answerbox 1
				if(this.parent.answer3.getValue() == this.parent.parent.xNumber || this.parent.answer1.getValue() == this.parent.parent.xNumber) {
					this.parent.answer0.setValue(this.parent.parent.yNumber);
				} else {
					this.parent.answer0.setValue(this.parent.parent.xNumber);
				}
			} else if (this === this.parent.back1){
				// Top Row, Answerbox 2
				if(this.parent.answer4.getValue() == this.parent.parent.xNumber || this.parent.answer0.getValue() == this.parent.parent.xNumber) {
					this.parent.answer1.setValue(this.parent.parent.yNumber);
				} else {
					this.parent.answer1.setValue(this.parent.parent.xNumber);
				}
			} else if (this === this.parent.back2){
				// Top Row, Answerbox 3
				this.parent.answer2.setValue(this.parent.parent.yNumber * this.parent.parent.xNumber);
			} else if (this === this.parent.back3){
				// Bottom Row, Answerbox 1
				if(this.parent.answer0.getValue() == this.parent.parent.xNumber || this.parent.answer4.getValue() == this.parent.parent.xNumber) {
					this.parent.answer3.setValue(this.parent.parent.yNumber);
				} else {
					this.parent.answer3.setValue(this.parent.parent.xNumber);
				}
			} else if (this === this.parent.back4){
				// Bottom Row, Answerbox 2
				if(this.parent.answer1.getValue() == this.parent.parent.xNumber || this.parent.answer3.getValue() == this.parent.parent.xNumber) {
					this.parent.answer4.setValue(this.parent.parent.yNumber);
				} else {
					this.parent.answer4.setValue(this.parent.parent.xNumber);
				}
			} else if (this === this.parent.back5){
				// Bottom Row, Answerbox 3
				this.parent.answer5.setValue(this.parent.parent.yNumber * this.parent.parent.xNumber);
			}
		}
		this.frame_57 = function() {
			this.gotoAndStop('static');
		}
		this.frame_98 = function() {
			this.gotoAndStop('static');
		}

		// actions tween:
		this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(12).call(this.frame_12).wait(10).call(this.frame_22).wait(30).call(this.frame_52).wait(5).call(this.frame_57).wait(41).call(this.frame_98));

		// Layer 4
		this.shape_80 = new cjs.Shape();
		this.shape_80.graphics.f().s("#000000").ss(0.5,1,1).p("ADCiXIAAEvImDAAIAAkvIGDAA").cp();
		this.shape_80.setTransform(19.8,14.8);

		this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_80}]}).wait(99));

		// Layer 6
		this.instance = new lib.blueBox();
		this.instance.setTransform(19.4,15.2,1,1,0,0,0,19.4,15.2);
		this.instance.alpha = 0;
		this.instance._off = true;

		this.timeline.addTween(cjs.Tween.get(this.instance).wait(58).to({_off:false},0).to({alpha:1},6).to({alpha:0},6).to({alpha:1},7).to({alpha:0},7).to({alpha:1},7).to({alpha:0},7).wait(1));

		// Layer 1
		this.instance_1 = new lib.redBox();
		this.instance_1.setTransform(19.4,15.2,1,1,0,0,0,19.4,15.2);
		this.instance_1.alpha = 0;
		this.instance_1._off = true;

		this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1).to({_off:false},0).to({alpha:1},5).to({alpha:0},6).to({alpha:1},6).to({alpha:0},4).wait(1).to({alpha:1},5).to({alpha:0},6).to({alpha:1},6).to({alpha:0},6).to({alpha:1},6).to({alpha:0},5).to({_off:true},1).wait(41));

		// whiteBox
		this.instance_2 = new lib.whiteBox();
		this.instance_2.setTransform(19.4,15.2,1,1,0,0,0,19.4,15.2);

		this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1).to({alpha:0},5).to({alpha:1},6).to({alpha:0},6).to({alpha:1},4).wait(1).to({alpha:0},5).to({alpha:1},6).to({alpha:0},6).to({alpha:1},6).to({alpha:0},6).to({alpha:1},5).wait(1).to({alpha:0},6).to({alpha:1},6).to({alpha:0},7).to({alpha:1},7).to({alpha:0},7).to({alpha:1},7).wait(1));

	}).prototype = p = new cjs.MovieClip();
	p.nominalBounds = new cjs.Rectangle(0,-0.3,39.2,30.8);


	(lib.textBox = function() {
		this.initialize();

		// timeline function:
		this.frame_0 = function() {
			this.answer0.tabIndex = 1;
			this.answer1.tabIndex = 2;
			this.answer2.tabIndex = 3;
			this.answer3.tabIndex = 4;
			this.answer4.tabIndex = 5;
			this.answer5.tabIndex = 6;
		}

		// Layer 1
		this.multipl2 = new lib.multipl1();
		this.multipl2.setTransform(47.5,40.5,1.003,1.003,0,0,0,8.2,7.6);

		this.multipl1 = new lib.multipl1();
		this.multipl1.setTransform(47.4,10.1,1,1,0,0,0,8.2,7.6);

		this.equal_mc1 = new lib.quest();
		this.equal_mc1.setTransform(159.5,8,1,1,0,0,0,7.5,5.2);

		this.equal_mc2 = new lib.quest();
		this.equal_mc2.setTransform(159.5,38.3,1,1.005,0,0,0,7.5,5.2);

		this.answer0 = new whizz.NumericInput("answer0");
		this.answer0.setTransform(-10,0,0.8,0.8);

		this.answer1 = new whizz.NumericInput("answer1");
		this.answer1.setTransform(70,0,0.8,0.8);

		this.answer2 = new whizz.NumericInput("answer2");
		this.answer2.setTransform(226.5,0,0.8,0.8);

		this.answer3 = new whizz.NumericInput("answer3");
		this.answer3.setTransform(-10,30,0.8,0.8);

		this.answer4 = new whizz.NumericInput("answer4");
		this.answer4.setTransform(70,30,0.8,0.8);

		this.answer5 = new whizz.NumericInput("answer5");
		this.answer5.setTransform(226.5,30,0.8,0.8);

		// Layer 2
		this.back0 = new lib.Back();
		this.back0.setTransform(7.5,11.4,1,0.815,0,0,0,19.4,15.2);

		this.back1 = new lib.Back();
		this.back1.setTransform(87.2,11.9,1,0.815,0,0,0,19.4,15.2);

		this.back2 = new lib.Back();
		this.back2.setTransform(243.9,11.6,1,0.815,0,0,0,19.4,15.2);

		this.back3 = new lib.Back();
		this.back3.setTransform(7.5,41.9,1,0.815,0,0,0,19.4,15.2);

		this.back4 = new lib.Back();
		this.back4.setTransform(87.2,42,1,0.815,0,0,0,19.4,15.2);

		this.back5 = new lib.Back();
		this.back5.setTransform(243.9,42,1,0.815,0,0,0,19.4,15.2);

		this.addChild(this.back0,this.back1,this.back2,this.back3,this.back4,this.back5,this.answer0,this.answer1,this.answer2,this.answer3,this.answer4,this.answer5,this.multipl1,this.multipl2,this.equal_mc1,this.equal_mc2);
		this.frame_0();
	}).prototype = p = new cjs.Container();
	p.nominalBounds = new cjs.Rectangle(-11.8,-5.1,275.6,68.5);


	(lib.quest = function() {
		this.initialize();

		// Layer 1
		this.text = new cjs.Text("=", "bold 23px Arial");
		this.text.textAlign = "center";
		this.text.lineHeight = 23;
		this.text.lineWidth = 26;
		this.text.setTransform(59.2,-6.2,1.021,0.999);

		this.tf_insect_name = new cjs.Text("ladybirds", "23px Arial");
		this.tf_insect_name.textAlign = "center";
		this.tf_insect_name.lineHeight = 26;
		this.tf_insect_name.setTransform(3,-7.5);

		this.addChild(this.tf_insect_name,this.text);
	}).prototype = p = new cjs.Container();
	p.nominalBounds = new cjs.Rectangle(-43,-7.5,120,37.7);


	(lib.multipl1 = function() {
		this.initialize();

		// Layer 1
		this.text_1 = new cjs.Text("x", "bold 23px Arial");
		this.text_1.textAlign = "center";
		this.text_1.lineHeight = 23;
		this.text_1.lineWidth = 26;
		this.text_1.setTransform(5,-7.6,1.021,0.999);

		this.addChild(this.text_1);
	}).prototype = p = new cjs.Container();
	p.nominalBounds = new cjs.Rectangle(-8,-7.6,30.9,30.6);

	(lib.LadybirdWing2 = function() {
		this.initialize();

		// Layer 1
		this.shape_30 = new cjs.Shape();
		this.shape_30.graphics.f("#990000").s().p("AkCg7QgGgBgFgBQgYgBgYAAQgWAGgZAJQglAMgUAiQgBABAAACQgBACAAACQgBADAAACQgNALAAAQQgCCdCdACQArAAAageQBrh9iYhlIAAAAAD4hbQBsh+iZhmQgFgCgFAAQgYgBgYAAQgXAGgYAIQgmAMgUAjQgBACAAACQAAADgBACQAAACgBACQgMALAAAQQgDCdCdACQAsABAZgeIAAAAAJNlxQAbAaASAOQANAKAbAkIAFAEIABABIhbBUQhEA0g5ApQgBACgdAYQgfAbgIAPQgWAZgeAfQhqBXhiBkIg6A9QhmBfiQCGQgZgniDhXQibhojLhJQACgGABgFQAKguAVgvQAVgqAFgOQALgiAWggQAYghAIgQQAaguAegpQAegpBBg4QBCg5Byg9QBzg+C3gqQDTgxDPBtQBVAsALALIAAAA").cp();
		this.shape_30.setTransform(71.5,54.2);

		this.shape_31 = new cjs.Shape();
		this.shape_31.graphics.f("#000000").s().p("AKclTIAaAfQASATAHARQABAFgcASQgwAug3AuQhvBkhsBYQh5B0hjBcQg5BBg8A+QgzA4hCAoIhEBEQgPAFgJgFQgFACgQgTQlKkMi+gQQgBgOAGgOQAIgSAAgDQANgmAJgbIAdhIQAKgagBgHQAlhSAZgeIAPgVQAAgBAng0QAng0BIgyQBMg2BVg0QBbg4B/gtQCIgxA/AGQC7gTCDBJQBcAzAEADIAtAkQAUAOAcAfIAAAAAJJloQgLgLhVgtQjPhsjTAxQi3AqhzA+QhyA9hCA5QhBA4geApQgeApgaAuQgIAPgYAiQgWAfgLAiQgFAOgVArQgVAvgKAtQgBAGgCAFQDLBJCbBoQCDBYAZAnQCQiHBmheIA6g+QBihkBqhXQAegfAWgZQAIgPAfgbQAdgYABgBQA5gqBEg0IBbhTIgBgBIgFgEQgbgkgNgKQgSgOgbgaIAAAAAD0hTQgZAegsAAQidgCADidQAAgQAMgLQABgCAAgDQABgCAAgCQAAgCABgDQAUgiAmgMQAYgJAXgGQAYAAAYABQAFABAFABQCZBnhsB9IAAAAAkGgyQCYBkhrB+QgaAegrgBQidgCACidQAAgQANgLQAAgCABgCQAAgCABgDQAAgCABgCQAUghAlgMQAZgIAWgGQAYAAAYABQAFAAAGACIAAAA").cp();
		this.shape_31.setTransform(71.9,53.3);

		this.addChild(this.shape_31,this.shape_30);
	}).prototype = p = new cjs.Container();
	p.nominalBounds = new cjs.Rectangle(0,0,143.8,106.7);


	(lib.LadybirdWing1 = function() {
		this.initialize();

		// Layer 1
		this.shape_32 = new cjs.Shape();
		this.shape_32.graphics.f("#990000").s().p("AhhjoQgmAMgUAiQgBADAAACQAAACgBACQAAADgBACQgMALAAAQQgDCbCdACQAqAAAZgcQBsh9iZhnQgFgBgDgBQgYgBgYAAQgXAGgYAJIAAAAAJOlxQAaAaATAPQAMAJAbAkIAFAEIABABIhbBUQhEA0g5ApQgBACgdAYQgfAbgIAPQgWAZgeAfQhqBXhiBkIg6A9QhmBfiQCGQgZgniDhXQibhojLhJQACgGABgFQAKguAVgvQAVgqAFgOQALgiAWggQAYghAIgQQAagtAegpQAegqBCg4QBBg4Bzg+QByg9C3grQDTgxDPBtQBVAsAMALIAAAA").cp();
		this.shape_32.setTransform(69.6,54.2);

		this.shape_33 = new cjs.Shape();
		this.shape_33.graphics.f("#000000").s().p("AKclTIAaAfQASATAHARQABAFgcASQgwAug3AuQhvBkhsBYQh5B0hjBcQg5BBg8A+QgzA4hCAoIhEBEQgPAFgJgFQgFACgQgTQlKkMi+gQQgBgOAGgOQAIgSAAgDQANgmAJgbIAdhIQAKgagBgHQAlhSAZgeIAPgVQAAgBAng0QAng0BIgyQBMg2BVg0QBbg4B/gtQCIgxA/AGQC7gTCDBJQBcAzAEADIAtAkQAUAOAcAfIAAAAAJKloQgMgLhVgtQjPhsjTAxQi3AqhyA+QhzA9hBA5QhCA4geApQgeApgaAuQgIAPgYAiQgWAfgLAiQgFAOgVArQgVAvgKAtQgBAGgCAFQDLBJCbBoQCDBYAZAnQCQiHBmheIA6g+QBihkBqhXQAegfAWgZQAIgPAfgbQAdgYABgBQA5gqBEg0IBbhTIgBgBIgFgEQgbgkgMgKQgTgOgagaIAAAAAhljgQAYgIAXgGQAYAAAYABQAFAAADACQCZBmhsB+QgZAcgqgBQidgCADibQAAgQAMgLQABgCAAgCQABgCAAgDQAAgCABgCQAUgjAmgMIAAAA").cp();
		this.shape_33.setTransform(70,53.4);

		this.addChild(this.shape_33,this.shape_32);
	}).prototype = p = new cjs.Container();
	p.nominalBounds = new cjs.Rectangle(-1.8,0.1,143.8,106.7);


	(lib.LadybirdBody = function() {
		this.initialize();

		// Layer 1
		this.shape_34 = new cjs.Shape();
		this.shape_34.graphics.f("#FFFFFF").s().p("Aj9jDQAAACAAACQAEAXAXAHQADAAADgBQAJgDAIgGQAEgHADgHQAEgJgDgJQgBgCgBgCQgJgLgPgCIAAABQgYACgIAWIAAAAAi8kaQCGATg0B0QgiBMhOgqQg2gcAIg+QAJhEBDgLIAAAAACiCyQgBgCgBgCQgJgLgPgCIAAABQgYACgIAWQAAACAAACQAEAXAXAHQADAAADgBQAJgDAIgGQAEgHADgHQAEgJgDgJIAAAAABdCyQAJhEBDgLQCGATg0B0QgiBMhOgqQg2gcAIg+IAAAA").cp();
		this.shape_34.setTransform(55.6,135.8);

		this.shape_35 = new cjs.Shape();
		this.shape_35.graphics.f("#000000").s().p("ALOlXQhri5iViIQgcgagkgQQi2hXjUAwQjiA+ipCHQhuBXhVB2Qg1BJglCPQFnB6DME6QAEAGAEAHQAhA0AXA3QAaAoAeAkQAYAcADAmQAAAKgBAKQAAAHAAAHQABAFAAAFQA8BGgjBaQAUgDAUgEQCEgdCohJQGqlEg1oIQgJhYgthNIAAAAAM3kJQBDDOgwDIQAYgEAVgDQAtgRAbAbQABABABACQABACAAABQABAGgEAFQgCACgBACQhDAYg1gXQgLAlgOAkQg5CaheBzQAzAcAoAoQABACABABQgBAEgBAEQgDAGgHADQg4gXgwgnQhkBxiKBIQAmA2AXBBQABABgCACQgEAIgKgBQgEAAgEgBQgrgzgXg/Qg3Abg8AUQiXAzihgCQgCAGgBAFQgTA8gzAmQgVAKgRgHQgGgCgFgEQgBgHgCgHQgDgHAAgHQAEgOAGgOQADgHAGgDQAKgEALACQADAAADgBQALABAGAIQAAABACABQAOgYAJgZQiUgJiChHQiRhOhWhDQhWhEgehDQgehDgIgRQgIgSgjh2QgThCADhVQgzAZgmAyQACADABAAQAKAFAFANQAAAEABADQAGANAAAOQgBAJgFAFQgLAMgMAJQgHABgIgBQgIAAgGAAQgGgFgFgGQgMgUACgcQAShLAygnQAkgeArgSQAFgpAJgrQARhPAihVQgqAGgugdQgigVgXgeQgGgJAEgJQACgHAHgCQAFgCADgBQAEABAEACQADABACACQArAtA/AUQADABAEABQAJgCAIABQAdhCAnhFQBDh1BohVQARgOARgMQgsgqgXg8QgBgBAAgCQAFgMANgBIAAAAQAEABAEACQADABACACQAeAwAhAuIABAAQC3h4DMhDQAHhFAPhAQAAgCADgBQAHADAGADQACABABACQAIA8gMA3QAHgCAFgCQHEhFDoFYQBaCFAxCWIAAAAAqogYQgJgCgJgCQgFAagFAZQAzAEAxAfQAAAEAAAEQAAAMgIAGQgpgMgsAAQgHAAgHAAQgFA3ADBUQAEBsAeBKQAdBJA0A1QA7AsBgBRQBgBRDDAxQAhAJAmACQAMhAgQhHQgKgqgTgkQADgKAJgDQADgBADgBQBDBMgIBxQgCAUgDAUQANAAAOgBQACgCABgCQACgBABgCQAAgCAAgCQABgGgEgFQgEgGgCgIQAAgBAAgCQAAgCAAgCQAAgBABgCQABgCABgCQABgDAAgEQgLgjgLgjQgFgPgEgOQgFgQgFgQQgJgigLghQgPgQgPgOQgagZAFgkQgKgXgLgVQgDgEgDgFQgDgEgEgDQgCgDgCgDQhviqish0QhRg2hTgoQghgKgggHIAAAAAqUDYQAJgWAYgCIAAgBQAOACAJALQACACABACQACAJgEAJQgCAHgFAHQgHAGgJADQgDABgDAAQgYgHgDgXQgBgCAAgCIAAAAAjyJPQACAJgEAJQgCAHgFAHQgHAGgJADQgDABgDAAQgYgHgDgXQgBgCAAgCQAJgWAYgCIAAgBQAOACAJALQACACABACIAAAA").cp();
		this.shape_35.setTransform(96.3,94.5);

		this.shape_36 = new cjs.Shape();
		this.shape_36.graphics.f("#333333").s().p("AKxliQAtBMAJBYQA1IJmqFDQipBKiEAcQgUAEgTAEQAjhbg9hGQAAgFAAgEQgBgIABgHQAAgKAAgKQgDgmgWgbQgggkgZgoQgYg3ghg1QgEgGgEgHQjLk6lnh6QAliOA0hJQBVh2BuhXQCqiHDkg+QDRgxC3BXQAkARAbAZQCVCIBsC6IAAAAArGgkQAhAHAgALQBUAnBRA3QCsBzBvCqQACADACADQADAEADAEQADAEAEAEQALAWAJAXQgEAjAZAZQAPAPAQAPQAKAiAKAiQAEAPAFAQQAFAPAEAPQALAjAMAjQgBADgBAEQAAACgBABQgBACgBACQAAACAAABQAAACABACQACAHAEAHQADAFAAAGQAAACAAACQgCABgBACQgCABgBACQgOABgOAAQAEgTABgVQAJhxhDhLQgDAAgDABQgJAEgDAJQASAkAKArQAQBHgLA/QgmgCghgIQjDgyhghQQhghRg7gsQg1g2gdhJQgdhKgEhsQgDhUAFg2QAGgBAHAAQAtAAApANQAIgHAAgMQAAgEgBgEQgxgegygFQAEgZAFgZQAJABAJACIAAAAApwB2QhDALgJBEQgIA9A2AdQBOAqAihMQA0h0iGgTIAAAAAlVJEQgIA9A2AdQBOAqAihMQA0h0iGgTQhDALgJBEIAAAA").cp();
		this.shape_36.setTransform(99.2,95.6);

		this.addChild(this.shape_36,this.shape_35,this.shape_34);
	}).prototype = p = new cjs.Container();
	p.nominalBounds = new cjs.Rectangle(0,0,192.5,188.9);


	(lib.FlyWing = function() {
		this.initialize();

		// Layer 1
		this.shape_37 = new cjs.Shape();
		this.shape_37.graphics.f().s("#000000").ss(0.1,1,1).p("ACWgPQAAABAAABACPAeQAAABAAAAIgCAAQgFAAgFgBQgCAAgBgBQgNgCgMgEQgcgEgpAEQgKABgKACQgFAAgFAAQAPAHAPAGQAqAQAiAFQAEAAAEABIABAAQABAAACAAQAAAAAAAAIABAAAB8A7QgBABAAABABNBdQgBABgBABAB3hLQABABAAABACDgRQACAAADAAQgDAAgCAAQgygGgpgZACWgPIgDgBQgGAAgFgBABuA8QAEAAAEABABnAXQgggKgdgTIgBAAQgEAAgDgBQhUgQhZgaAheheQBBAeA/APQADAAADABIAAAAQAdgYAygDAAOAaQgFgBgFAAABuA8QgfgCgnAFQgDAAgDAAQAAAAgBAAQgMACgMACQgBAAAAAAQAAAAABAAQANAIAMAGQAXALASADAhnBOIBwgLAiVAJQBPAFBKALAAqgGQAtgNAsAC");
		this.shape_37.setTransform(15.2,12.1);

		this.shape_38 = new cjs.Shape();
		this.shape_38.graphics.f().s("#000000").ss(1,1,1).p("AB5hEQADAEAEAEQACACACACQACADACAEQAGAJAEAKQADAKACALACXgIQAAAFAAADQAAAHgBAHQgCALgEAKACPAlQgDAGgEAHQgBABgBABQgBACgBADQgEAEgEAEAB7BCQAAABgBAAQgDADgDADQgDADgDACQgCACgBABQgFADgFAEQgJAGgKAFABLBkQgTAIgWAEQgQADgSAAQg7AAgsgfQgBgCgCgBQgCgBgBgBQgigcgGgkQgBgIAAgHQAAgXALgVQAMgUAVgQQAGgFAGgDQApgaA1AAQASAAAQADQApAHAgAYQAGAFAGAG");
		this.shape_38.setTransform(15.2,11.5);

		this.shape_39 = new cjs.Shape();
		this.shape_39.graphics.f("rgba(204,204,204,0.714)").s().p("AB5hEQADAEAEAEQACACACACQACADACAEQAGAJAEAKQADAKACALQAAAAAAABQAAAFAAADQAAAHgBAHQgCALgEAKQAAABgBABQgDAGgEAHQgBABgBABQgBACgBADQgEAEgEAEQAAAAgBABIgBAAQAAAAAAAAQgBAAgCAAIgBAAQgEgBgEAAQghgFgrgQQgOgGgQgHQAFAAAFAAQALgCAJgBQApgEAdAEQAMAEAMADQACAAACAAQAEABAGABIABAAIgBAAQgGgBgEgBQgCAAgCAAQgMgDgMgEQgdgEgpAEQgJABgLACQgFgBgFAAIAAABQAQAHAOAGQArAQAhAFIAAAAQAEAAAEABIABAAQACAAABAAIAAABQgDADgDADQgDADgDACQgCACgBABQgFADgFAEQgJAGgKAFQgBAAgCABQgTAIgWAEQgQADgSAAQg7AAgsgfQgBgCgCgBQgCgBgBgBQgigcgGgkQgBgIAAgHQAAgXALgVQAMgUAVgQQAGgFAGgDQApgaA1AAQASAAAQADQApAHAgAYQAGAFAGAGQABAAABABIAAAAACIgLQAGAAAFABIAEABIgEgBQgFgBgGAAIAAAAACEgMQACAAACABQgCgBgCAAIAAAAQgtgCgsANQAsgNAtACIAAAAAApgrQApAZAyAGQgygGgpgZIAAAAAAEAeQhKgLhPgEQBPAEBKALIAAAAAAJBJIhwALIBwgLABoAcQghgKgcgTIgCABQgDgBgEgBQhTgQhagaQBaAaBTAQQAEABADABIACgBQAcATAhAKIAAAAAhehYQBBAdA/APQADAAADABIABAAQAdgYAxgCQgxACgdAYIgBAAQgDgBgDAAQg/gPhBgdIAAAAABuBBQgfgBgnAEQgDAAgDAAQAAAAAAAAQgMACgNACQANgCAMgCQAAAAAAAAQADAAADAAQAngEAfABIAAAAAAJBIQAAAAAAAAQAAAAAAABQAOAHALAGQAYALARADQgRgDgYgLQgLgGgOgHIAAgB").cp();
		this.shape_39.setTransform(15.2,11.5);

		this.addChild(this.shape_39,this.shape_38,this.shape_37);
	}).prototype = p = new cjs.Container();
	p.nominalBounds = new cjs.Rectangle(0,0,30.3,23.1);


	(lib.FlyBody = function() {
		this.initialize();

		// Layer 1
		this.shape_40 = new cjs.Shape();
		this.shape_40.graphics.f("#000000").s().p("AAXgWQAAgBABgBQABgBAAAAQABAAABABQAAACAAABQAAABgBAAQgBABgBAAQAAAAgBgBQAAgBAAgBIAAAAAAGhQQAXADAOAUQAOAUgDAZQgDAYgSAQQgBACgCABIAAAAQgGAFgCAMQAEALAFAKQgBABAAAAQAAABgBAAQAAAAgBAAQgBgBAAAAQgFgLgEgKQAAgBAAAAQACgHACgEQgDABgDACQgGAIgGAIQAAAMADAGQABABAAAAQAAABgBAAQAAABgBAAQgBAAAAgBQgEgHAAgNQAAgBAAAAQAFgHAFgHQgFABgEABQgFAIgGAJQAAAMAEAGQAAABAAAAQAAABAAAAQgBABgBAAQAAAAgBgBQgEgHAAgNQABgBAAAAQAGgJAFgHQgCAAgDgBQgKgBgIgEQACAJABAIQAAABAAAAQgDANgEAGIAAABQgBAAAAgBQAAAAAAgBQAAAAAAgBQAEgFACgMQgCgKgBgJQgEgCgDgDQACAIABAIQAAAAAAABQgDANgEAGIAAAAQgBAAAAAAQAAgBAAAAQAAgBAAAAQAEgGACgLQgCgKgBgJQgBgBgBgBQABAEAAAGQAAAAAAABQgHAJgHAKQAAAAgBABQgBgBAAAAQgBAAAAgBQAAAAAAgBQAHgJAGgJQABgNgFgGIAAAAQgNgSADgYQAAgDABgDQABgFACgEIAAgBQABgEACgDQAFgLAJgIQASgQAUACIAAAAAApg3QgOgUgVgCQgTgCgRAQQgJAHgEAKQgCADgBAEIgBAAIAAABQgBAEgBAEQgBADAAADQgDAYANARQAAAAABABQACAEAEADQAAABAAAAQAEAEAFADIABAAQAIAFAKABQAJABAKgDQABgBACAAQAEgCAEgDQACgBACgBQABgCACgBQAQgQADgWQADgZgNgSIAAAAAgSgfQAAgCABgBQABAAABAAQACAAABABQAAABAAABQAAABgBABQgBABgBAAQgBAAgBgBQgBgBAAgBIAAAA").cp();
		this.shape_40.setTransform(5.5,8.2);

		this.shape_41 = new cjs.Shape();
		this.shape_41.graphics.f("#FFFFFF").s().p("AALgIQAFgEAGABQAGAAADAFQAEAGgBAEQAAAHgFAEQgFAEgGAAQgGgBgDgFQgEgFABgHQABgEAEgFIAAAAAASANQAAABAAABQABABAAAAQABAAABgBQABAAAAgBQAAgBAAgCQgBgBgBAAQAAAAgBABQgBABAAABIAAAAAgTgSQAFABAEAFQADAEAAAHQgBAEgEAEQgFAEgFgBQgFgBgEgEQgDgFAAgEQABgGAEgEQAFgEAFAAIAAAAAgXAEQAAABABABQABABABAAQABAAABgBQABgBAAgBQAAgBAAgBQgBgBgCAAQgBAAgBAAQgBABAAACIAAAA").cp();
		this.shape_41.setTransform(6,4.5);

		this.shape_42 = new cjs.Shape();
		this.shape_42.graphics.f("#666666").s().p("AAQgZQgEAEgBAHQgBAGAEAGQADADAGAAQAGABAFgCQAFgFAAgGQABgHgEgFQgDgFgGgBQgGAAgFAEIAAAAAApgkQANATgDAWQgDAZgQAQQgCABgBABQgCABgCACQgEACgEACQgCABgBAAQgKAEgJgBQgKgBgIgFIgBgBQgFgDgEgDQAAgBAAAAQgEgDgCgEQgBgBAAgBQgNgTADgVQAAgDABgDQABgFABgEIAAAAIABgBQABgDACgEQAEgKAJgHQARgQATADQAVACAOATIAAAAAgOgjQgFgBgFAEQgEAEgBAHQAAAGADAEQAEAFAFAAQAFABAFgEQAEgEABgGQAAgGgDgFQgEgEgFgBIAAAA").cp();
		this.shape_42.setTransform(5.5,6.2);

		this.addChild(this.shape_42,this.shape_41,this.shape_40);
	}).prototype = p = new cjs.Container();
	p.nominalBounds = new cjs.Rectangle(0,0,11,16.3);


	(lib.BeeSingleWing = function() {
		this.initialize();

		// Layer 1
		this.shape_43 = new cjs.Shape();
		this.shape_43.graphics.f("#000000").s().p("ABKgUQAIANAJALQAHAPALANIAAABQABADABACIABABQAEALAFALQABAFAAAFQABAHABAHQgCgEgBgCQAGARAHARQAAgCAAgDQABADABACQACADABAEQAAAIgBAJQgRAAgPgJQgEgCgGgDQgBAAgBAAQgDgCgFgBQgCgCgCAAQgBgBgBAAIgBAAQgKgEgIgDQABgCAEADQgEgDgIgDQgIgCgHgEQADACADADQgJgFgJgDQgjgQgcgbQgGgJgHgGQgBAAAAgBQgBgBgBgBQgEgFgEgFQgDgHgFgDIgBgBQgEgDgDgBQABABABADQgCgCgDAAQgCgBgBgBQgDgEgDgCIgCAAQgKgMgLgQQgEgFgCgDQgDgJgDgIQAAABABABIAAgBQgBgCAAgDQAAgFgDgDIAAgDIACAAQgCgCAAgBIgBAAIAAABIgBAAQgBAAAAgBQgDgDgBgCQgHgXAEgZQAAgBABAAQAHgGAHgFQAEgBABgDQAKAAAKAAQAiAJAiAKQAuAOAcArQAOATAOAVIAAAAAAfhEQgKgJgJgFQgCgCAAgBQgOgLgRgKQgEAAgCgBQgBAAgCAAQAAgCgBAAQgqgQgrABQgBAAgBAAQgCACgBABQgFAnAPAgQABADACAFQAMAYAXASQABAAAAACIACAAQAAABABABQAGAFAGAGQAPAPAQANQAIAEAGAIQAqAeAwAXQAEACAFADQABAAADAAQAOAEAPAAQABgMgBgMQgUgugWgtQgSgigXgdQgDgBgBgCQgBgBgBgCIAAgBABvA1QABAFADAFQACAFADAEQgEgGAAgFQgCgFgDgDIAAAAABpB5QAJACAIADQgBgDAAgBQgJgBgHAAIAAAAAB6B1QAEAAADAAQgDgJgEgHQAAAHAAAJIAAAAAB7B6QAAADADACQADAAAEABQgBgDgCgDQgDAAgEAAIAAAAAAyBlQg1gdgvgqQANARATAKQAUAWAcANQAJAFALAEIAAAAAiFhqIAAACQAAACABABQAAABAAADQAAABACAAQAAgIAAgIQgCAFgBABIAAAA").cp();

		this.shape_44 = new cjs.Shape();
		this.shape_44.graphics.f("rgba(255,255,204,0.502)").s().p("AAfhGQgJgIgKgGQgBgBAAgCQgPgKgRgKQgDAAgDgBQgBgBgBAAQAAgCgBAAQgqgPgrABQgCAAgBAAQgBABgBABQgFAnAOAgQACAEACAFQAMAYAXATQABAAAAAAIABAAQAAABABACQAGAEAGAGQAQAPAQANQAIAEAGAIQApAeAwAXQAFACAFADQABABACAAQAPADAOAAQABgMgBgMQgTgugXgtQgSgigXgdQgCgBgBgBQgBgBgCgDIAAgBABwAzQABAGACAEQADAFACAEQgDgGAAgFQgDgFgCgDIAAAAAB7BzQADAAAEAAQgEgIgDgIQAAAIAAAIIAAAAABqB3QAIACAJADQgCgDAAgBQgIgBgHAAIAAAAAB8B4QAAADACACQAEAAADABQgBgDgBgDQgEAAgDAAIAAAAAAzBjQg2gdgugqQANARATAKQAUAWAbANQAKAFALAEIAAAAAiChxQgBAEgBACIAAABQAAADABABQAAABAAACQAAACABAAQAAgJAAgHIAAAA").cp();
		this.shape_44.setTransform(0,0.1);

		this.addChild(this.shape_44,this.shape_43);
	}).prototype = p = new cjs.Container();
	p.nominalBounds = new cjs.Rectangle(-13.8,-13.7,27.8,27.4);


	(lib.BeeBody = function() {
		this.initialize();

		// Layer 1
		this.shape_45 = new cjs.Shape();
		this.shape_45.graphics.f("#666666").s().p("ABBAXQgHAAgHgCIgCgBQAAABgBgBIABgBQgEgDgFgCQAAgCAAgCQgHgHgCgHQAEgBABgDQgCgBgCgCIABgCQgCgBABgBQAAgEABgDQgBAAgBAAIgCAAQABgBAAgBQABgEACgDIAAgBIABAAIACgEQAEgBAAgCIAAgBIACAAIAAgBQABgDACABQABAAgBABQAAADgCADIAAACIgBgBIgCAEQgBAAgBABQAAACABACQgBACAAADQAAADAAACQAAADABABQgBABAAACQACAAgBABQgBABAAABIAAACQACAAACABIAAABQAAABAAABQABABABACIgBACIAAABQABAAABACQABAAABABQAAgBADAAIgBAEQABABAAABIAAABIABAAIABAAQAFABAEABQACAAACABIABAAIAAABQANgFALgCQABgCABABIAAgBQABgDAAgBQACAAACgBIAAgBQABgDABgBIABAAIABAAIABAAIAAAAQACAAABAAQAAAAgBABQAAAEgCAEIAAABQgCAAAAABQgBABgBABIgBABIAAAAQgDABgDACQgDABgCACQgEAAgCABQgFABgFABQgCAAgDAAIAAAAAgLAXIgBgCQABgDACgDQAAgDABgBIgBgCQADgBADgBIAAgDQAAgBgBgBQgBgCADAAQgBgBgBgCQACgCgBgDQABgEgBgEQAAgFgBgDQACgDgBgDQgBgCgCAAIgCgFIgDABIAAgCQgCgGgBgEQgBgCACAAQACgBACAEIABACIACAAIAAACQABADAFABIABAFIACAAIABACQABAFACAGQAAACABACIgCAAQgCAAAAgBQABAFAAAGQAAABgBABIABAEQgEABgBACQAAAEAFABQgCAOgJALQABADgBADQgHADgGAEIABABQgCACAAgCIgCABQgPAFgOgBQgIgCgHgBQgDgCgGAAQgDgCgFgBQgEgEgFgBIAAgBIgCgBQgBgCgBgBQgBgCgCABIgBgCQgCgGAAgGQgBgBgBgBQACgBACAAIABgBIABAAIABACIACAAQABACACAEIAAACQADABADAAQAAACACAEIAAACQACgBABACQARAEASAHIABgBQADgBAEAAQAHgCAHgBIACAAIACgBIAAgCQAAgBAAgBIgBgGQAEgBABACQABgBACgBQABgCABgBIAAgC").cp();
		this.shape_45.setTransform(17.7,-7.8);

		this.shape_46 = new cjs.Shape();
		this.shape_46.graphics.f("#FFFFFF").s().p("AhDggQACgDAAgCQAOgDAKAHQgMACgOgBIAAAAAhWACIgDgBQAFgKAJgKQgGAMgFAJIAAAAAhRAmIgBgCQgFgGAAgIQAFAJABAHIAAAAAhAAbQADABgCADQgCACAAAEIAAgCQgCgDACgDQgBgCACAAIAAAAAgvgUQAGgEAIADQAAABADAAQAEAEAAAHQgLAAgHgEIgDgCQgCgEACgBIAAAAABJgeQABACABACQgHAAgHgBQgBAAgCAAQACgBABgBQAGgCAGABIAAAAABagDIgCAAQgDgHgFgHQAGAGAEAIIAAAAABKANQABACgBADIgBABQAAgDgBgCQgBgBACgBQACAAgBABIAAAAABVASIAAACQAAgGADgFQAAAFgDAEIAAAAAA8gOQgFADgHAAQAAgFACgDQADAAAAAAQAFgCAEACIAAABQAAABABABQgBABAAAAIgCAB").cp();
		this.shape_46.setTransform(18.1,-9.3);

		this.shape_47 = new cjs.Shape();
		this.shape_47.graphics.f("#333333").s().p("ADDh2QAGAAAIABQACAAABAAQACAFADADQATAUgFAWIgBAAIgBABIgBAAQgBACgBADIAAABQgCABgCAAQAAABgBADIAAABQgBgBgBACQgLACgNAFIAAgBIgBAAQgCgBgCAAQgEgBgFgBIgBAAQgBgBAAAAQAAgBgBgBIABgEQgDAAAAABQgBgBgBAAQAAgCgCgBIABgCQgBgCgBgCQAAgCAAgBIAAgBQgCgBgCAAIAAgCQAAgBABgBQABgBgCAAQAAgCABgBQgBgBAAgDQAAgCAAgDQAAgDABgCQgBgCAAgCQABgBABAAIACgEIABABIAAgCQACgDAAgDQAIgIANgBIAAAAAjkCAIAAACQgBAAgCAAQACgCABAAIAAAAAA/hyQAPABALgCQgKgHgNADQgBACgCADIAAAAABxhzQABAEACAGIAAACIADgBIACAFQACAAABACQABADgCADQABADAAAFQABAEgBAEQABADgCACQABACABACQgDABABACQABABAAABIAAADQgDABgDABIABACQgBABAAADQgCADgBADIABACQgCACAAADQgCABgBABQgBgCgEABIABAGQAAABAAABQgBABgBACIgCAAQgHABgHACQgEAAgDABIgBABQgSgHgRgEQgBgCgCABIAAgCQgCgEAAgCQgDAAgDgBIAAgCQgCgEgBgCIgCAAIgBgCIgBAAQgHgiAcgeQAEgFADgHQACAAADgBQAjgEARARIAAAAAAthOQAFgLAFgMQgIAKgFAMIADABAAygqQgBgHgFgJQAAAIAFAGIABACABThmQgCABACAEIADACQAIAEALAAQAAgHgEgEQgDAAAAgBQgJgDgGAEIAAAAABDg1QgDAAABACQgCADACADIABACQAAgEACgCQACgDgDgBIAAAAADehVQgEgIgFgGQAEAHADAHIACAAADOhwQgHgBgGACQgBABgCABQACAAACAAQAGABAIAAQgCgCAAgCIAAAAADAhgIACgBQABAAAAgBQAAgBgBgCIAAAAQgEgCgFACQAAAAgCAAQgDADAAAFQAHAAAFgDIAAAAADZg+QADgEAAgFQgDAFAAAGIAAgCADOhDQABgBgCAAQgCABABABQACACAAADIAAgBQACgDgCgCIAAAA").cp();
		this.shape_47.setTransform(4.8,-1.1);

		this.shape_48 = new cjs.Shape();
		this.shape_48.graphics.f("#FFCC00").s().p("ACQiYQgHAGgIAHQgMALAAAQQACAAABAAQAAABACAAQAAADAAADQAAASABAQQACAAABACQgBACAAACQgFANADAKQAFACADgCQAAACAAABQgCAEACAFIAAABQAAACAAACIAAABQAEAGAFAIQgGgCgGACQAAABAAACQAAADABAEQAIAHAKAIQgJABgGADIAAACQAAABAAACQAEAEAIAAQgFAAgEACQgEgFgGgEIAAgCIABAAQgEgJgFgJQgDgBgBgDQgIgggSgaQgMgTADgTQACgCABgBIAAgCQADgNADgMQACgFADgBQAGgIABgJQAXAAAWAAIAAAAAh8g7QgDAUgCAUQAAAUAHAXIAAABIABACIAAADQAAABAAACIAAABIABACQAAAHAFAIQADAGAFAEQANAXARAWQAQAYAaARQAEADAEABQgEACgGAAQgJgCgGgBIAAgCQAAgBAAgCIAAgBQgCgCgBAAQgYACgSgRQAFACAEgCQAAgBAAgCIABAAQgQgPgRgNIgBgCQgDgNgJgJQgCAAAAABIgBgBIAAgCQAAgBgCgCQgBgDgCgEIgBAAQgGgaADgcQAAgYAEgYQACgEADgEQAHgKAIgJQgBAEAAAFIgCAAIAAABAAziWQgEATgDAXQgDAkABAnQACADAEABQADAFACAFQABAAACABQATASAPAZQAAACAAABIAAACQAMAMAMAMQgPAHgNALQgFADgDABQgPgPgTgJQgGgNgIgMIAAgCQABgBACAAQgGgVgLgSQgHgQgDgRQgGgeAAgfQAAgCAAgBQAKgRACgSQATgDAUAAIAAAAAhFhyQARgKATgHQgHAUABAYQACAHgCAIQgGAgAIAfIAAACIACABIAAADIABACIAAABQAAABAAACQAAABABACQAEAQAFARQAEAGAEAGIAAABQAQASAMAUQAEACAEADQgCACgDADQACAEADAGIABAAQAAACACADQACAAAAABQACADACADQgEAEgFADQgCABgCACQgCgGgGgCIgCgBIgBAAQgJgGgMADQgGgIgHgGQgIgJgDgHQABAAAAgCQACgBAAgCQgMgNgJgOQgCgBAAgCQAAgBgBgCQgBgBAAgCQAAgBgCgCQgIgPAAgPQAAgdgJgdQACgDAAgDQgDgeAQgYIAAgDQACgCAAgBQACgDgCgBQAAgCgCAAQgBAAgCAAIAAAA").cp();
		this.shape_48.setTransform(-11.9,-5.2);

		this.shape_49 = new cjs.Shape();
		this.shape_49.graphics.f("#FF9900").s().p("ABTgxQAFABAMACQAKABgNAMQgFAAgGACQgtAEgcAhQgFAEgEADQgEADAAAIQgCAKAAAMQAAASACARQgDgUgFgTQAAgCAAgDQgBgNAGgMQAEgIAGgEIABAAQACgDABgBQAAgCAAgBIAAgCQgBgDgDAAQgNgEgCgPQAAgCgBAAIgCAAQgBgBAAgCIAAgBIABgCIACAAIAAgBQAEgDgDgFIAAgBQACgDgBgBQAHABAHADQANAEADgKQACgDgCgCQgHgEgJgDQgSgFgVgBQgkgCgkAAQAMgEgEgLQAogBAnABQAWAIAXAHQAMAFAHgGQAMADAAgLQAJADAJAFQgBABABACQACAAAAABIgCACIAAABQgDAAgBACIgCAAIAAADQACAHAHADQgBACAEADIAAAAAgaBMIACAAQAAACAAABIgCgBIAAgCAABBVQAAADAAADQAAgDgBgBIABgC").cp();
		this.shape_49.setTransform(7,-14.6);

		this.shape_50 = new cjs.Shape();
		this.shape_50.graphics.f("#000000").s().p("AD3g+IgBAAIAAgBQAAAAABABIAAAAAEGiCQgNABgIAIQABgBgBAAQgCgBgBADIAAABIgCAAIAAABQAAACgEABIgCAEIgBAAIAAABQgCADgBAEQAAABgBABIACAAQACAAAAAAQgBADAAAEQgBABACABIgBACQACACACABQgBADgEABQACAJAHAHQAAACAAACQAFACAEADIgBABQABABAAgBIACABQAHACAHAAQgCAXgFAWQgEALgFAOQgGAPgPAJQAAAYgPARQgBABgCgBQgEgCgCgDIADgCIACAAQAEgCACgFQABgLAAgJQAAgBgBAAQgDAAgDAAQgCgFgPgBIgJAHIAAACQAAABACACQADAEAEACQgBADgDABQgGgEgDgIQgDgNgMgDIAAAAQgDAagJAaQgDAMgGAKQgBAAAAACQgGAJgGAJQgDABgFACQgBgCgCAAQgBgNAHgOQADgFACgIIAAgCIABAAQgBgDAAgBQAAgBABgCIAAgCIACAAIAAgDQADgIADgKQAAgBABgCQAAgBACgCIABAAIAAgEIACAAIAAgCIABgBQACgCABgDIAAgBQAEgFACgFQgCgBgBgCQgRgCgKgMQgGgGgGgFQgCAAgCgBQAHAQADARQADAJgBAHQgCAigKAfQgDAMgGALQgCAAAAABQgGAJgGAJQgDACgEABQgCgBgBAAQgCgOAIgOQADgGABgHIAAgCIACAAQgCgCAAgCQAAgCACgBIAAgBIABAAIAAgEQADgJADgJQAAgBACgBQAAgCABgCIACAAIAAgEIABAAIAAgCIACgBQABgCACgCIAAgCQAMgOgGgTQgCgDgBgFIgCAAQAAgBgBAAQgIgOgKgJQAAAAgCAAIAAAAQgKABgRASQgFADgFACQAJAVAEAWQADAJgBAHQgCAigKAfQgDAMgGALQgCAAAAABQgGAJgGAJQgDABgEACQgCgCgBAAQgCgNAIgNQADgGABgIIAAgCIACAAQgCgCAAgCQAAgBACgCIAAgBIABAAIAAgDQADgJADgKQAAgBACgBQAAgCABgCIACAAIAAgEIABAAIAAgCIACgBQABgCACgCIAAgCQAMgNgGgUQgCgDgBgFIgCAAQAAgBgBAAQgIgOgKgJQAAgBgCAAIAAgCIAAAAQgKAFgKAGQAMAbAFAaQADAIgBAIQgCAhgKAfQgDANgGAKQgCAAAAACQgEAJgGAJQgDABgEABQgCgBgBAAQgCgOAIgNQADgGABgHIAAgCIACAAQgCgDAAgBQAAgCACgBIAAgCIABAAIAAgDQADgJADgJQAAgBAAgCQAAgBABgCIACAAIAAgEIABAAIAAgCIACgCQABgBACgDIAAgBQAMgOgGgTQgCgEgBgEIgCAAQAAgBgBAAQgIgOgIgJQAAgCgCAAIAAgBQgBgCgBgBQgFAFgFAFQgJALgLAHQADAKACALQADAJgBAHQgCAigKAfQgDAMgGALQgCAAAAABQgGAJgGAJQgDABgEACQgCgCgBAAQgCgNAIgNQADgGABgIIAAgBIACAAQgCgEAAgBQAAgBACgCIAAgBIABAAIAAgEQADgIADgKQAAgBACgBQAAgCABgBIACAAIAAgFIABAAIAAgBIACgCQABgCACgCIAAgCQAMgNgGgUQgCgDgBgFIgCAAQAAgBgBAAQgCgEgDgEQgHACgIAAQgCAAgBAAQgGAEgFADQAIAWAFAVQADAJgCAIQgBAggLAgQgDAMgGALQgBAAAAABQgGAJgGAJQgDABgFACQgBgCgCAAQgBgNAHgNQADgGACgIIAAgBIABAAQgBgEAAgBQAAgBABgCIAAgBIACAAIAAgEQADgIADgJQAAgCABgCQAAgBACgBIABAAIAAgFIACAAIAAgCIABgBQACgBABgEIAAgBQAMgOgGgTQgBgDgCgFIgBAAQAAgBgCAAQgHgOgLgIQAAgCgBAAIAAgBQgGAEgFABIgCAAQgBACgCAAQgDACgEAAQgSACgRgBIAAgBQgVgCgTgIQgYgHgMgYQgRghgGgkQgDgNACgRQAAgeABgeQADgZARgSQAHgIAJgHQAYgRAdgMQAfgQAjgOQABAAACgBQAegMAAgaQASgHATgDQAMgCAOgBIAAgCQABgBACgCQABgBADAAQACgCAAAAQgGgDgGgBQAXADAbgCQAIACAHADQgBgFABgBQAGgCAJgBQAVAHAUAJQAEgGAJACQAOAHAQAFQAIABAGACQAQAHAPAJQAIAJAQAGQACACABABQADADACADQABADACADIgCACIAAABQACACABADQACADADADIABABQAUADgCASQAAAFgBAEQAAACAAABQAIAGgCAKIAAAAACsjDQgFgDACgCQgIgDgBgHIAAgDIABAAQACgCADAAIAAgBIABgCQAAgBgBAAQgCgCACgBQgJgFgJgDQAAALgMgDQgIAGgMgFQgWgHgYgIQgngBgnABQAFALgMAEQAiAAAkACQAVABATAFQAJADAIAEQABACgBADQgDAKgOgEQgIgDgIgBQABABgBADIAAABQADAFgFADIAAABIgBAAIgCACIAAABQAAACACABIABAAQACAAAAACQABAPAPAEQADAAACADIAAACQAAABAAACQgCABgBADIgCAAQgGAGgGAIQgGAMACANQAAADAAACQAEATAFAUQgDgRAAgSQAAgMABgKQACgIAEgDQAFgDAEgEQAdgjAtgEQAGgCAEAAQAOgMgLgBQgMgCgEgBIAAAAABfg/IgBABQgCAAgCABQABABABABQAAAGACAGIABACQACgBABACQABABABACIACABIAAABQAFABAEAEQAFABADACQAGAAADACQAHABAIACQAOABAPgFIACgBQAAACACgCIgBgBQAGgEAHgDQABgDgBgDQALgLACgOQgFgBgBgEQACgCAEgDIgBgEQABgBAAgBQAAgGgBgFQAAABACAAIACAAQgBgCAAgCQgCgGgBgFIgBgCIgCAAIgCgFQgGgBgBgDIAAgCIgCAAIgBgCQgCgEgCABQgCAAABACQgRgRgjAEQgDABgCAAQgDAHgEAFQgcAeAHAiIAAAAAAsi6IACAAIgCgCIAAACAArjMQgXAAgUAAQgCAJgGAHQgDACgBAEQgDAMgDAOIAAABQgCACgBABQgDAUAMASQAQAbAHAfQACADADADQAEAJAFAJIgCAAIAAACQAGAEAFAFQAEgBAFgBQgIAAgEgEQAAgCAAgBIAAgCQAGgDAJgBQgLgIgHgJQgCgEAAgDQAAgCAAgBQAGgCAGACQgEgIgFgGIAAgBQAAgCAAgBIAAgCQgBgEABgFQAAgBAAgCQgDACgEgCQgDgKAEgMQAAgDACgCQgCgBgBAAQgCgRAAgSQAAgDAAgDQgBAAAAgBQgCAAgBAAQAAgPAMgMQAHgGAIgGIAAAAACsglQABgCABgBIAAACIgCABAC3g2IAAACQgBABgBACQAAgDACgCIAAAAAA9hEIAAACIABABQAAgBAAgCIgBAAABZg7IgBACQABABAAADQAAgDAAgDIAAAAADvhIQACABAAACQgBgCgBAAIAAgBAjhhvIAAgCIABAAQAAgEACgFQgIAJgHALQgDADgCAEQgEAYAAAaQgDAcAGAYIABAAQACAEABADQACACAAABIAAACIABABQAAgBACAAQAJAJADANIABACQARANAQAQIgBAAQAAABAAABQgFACgEgCQASARAYgCQABAAACACIAAABQAAACAAACIAAABQAGABAJACQAGAAAEgCQgEgBgFgDQgZgRgRgYQgQgWgOgXQgEgEgDgEQgFgIAAgHIgBgCIAAgBQAAgCAAgBIAAgDIgCgCIAAgBQgGgXAAgWQACgUADgTIAAAAAjbhdIAAABIABAAIgBgBAgwjLQgUAAgTADQgCASgKARQAAABAAACQgCAfAIAeQADARAHAQQALAUAGAVQgCAAgBABIAAACQAHAMAGAMQAUAIAPAPQADgBAEgDQAOgLANgHQgMgKgKgMIAAgCQAAgBAAgCQgPgZgUgUQgBgBgCAAQgBgFgDgEQgFgCgBgDQgCgnADgkQADgWAFgUIAAAAAiAi5IAAgBIgBABIABAAAiqinQACAAABAAQACAAAAACQABABgBADQAAACgCABIAAADQgQAYADAeQAAADgCADQAJAdAAAfQAAAPAIAPQABACAAABQAAACACAAQABABAAABQAAACACABQAJAOAMANQAAACgCABQAAACgBAAQADAHAHAJQAIAGAGAIQAMgDAKAGIACAAIABACQAGABADAGQACgCABgBQAFgDAFgDQgDgDgCgEQAAgBgBAAQgCgDAAgCIgBAAQgDgGgCgEQADgDACgCQgEgCgEgDQgOgUgQgRIAAAAQgFgGgDgGQgGgRgDgQQgBgCAAgBQAAgCAAgDIAAgBIgCgCIAAgDIgBgBIAAgCQgIgfAGggQACgHgCgIQgBgYAHgTQgTAGgRAKIAAAAAiBitIAAACIABAAIgBgCAiDiQIAAABQAAgBACAAIgCAAAiqBkQgBAAgCAAQACAAADACIgCgCAjqAoIAAABIABAAIgBgB").cp();
		this.shape_50.setTransform(-1.8,0);

		this.addChild(this.shape_50,this.shape_49,this.shape_48,this.shape_47,this.shape_46,this.shape_45);
	}).prototype = p = new cjs.Container();
	p.nominalBounds = new cjs.Rectangle(-28.1,-26.8,56.5,53.7);


	(lib.Background = function() {
		this.initialize();

		// Layer 1
		this.shape_51 = new cjs.Shape();
		this.shape_51.graphics.f().s("#666633").ss(1,1,1).p("AF9nPQj0DcA4DzQBmFGBsBJAGRGSQAPAKgfAXQgOgIgnAIQgnAJgRgRQgVgVg2ASQgMAVg4AEQACAbgggDQgegEgvAFQgXANgRgTQgPgOguAFQgegPg/gGQgHAVgegZQhGgFhRgDQgNgcgaAAQgFAGgFAFAltneQDIDkglD6QgBAJgGAJQgtDeiNCeAjNAAQgCAJgCAJAmVGPQAFgBAFAA");
		this.shape_51.setTransform(557.6,273);

		this.shape_52 = new cjs.Shape();
		this.shape_52.graphics.f("#666633").s().p("AmQGoQCNieAtjeQAGgJABgKQAlj5jIjkQAQgJAOgMQABgBABgBQBVA+B2AAQB6AABVhCQAPgMANgNQAJAIALAHQBSA4B0AAQAeAAAcgEQj0DcA4DyQBmFHBsBJIgCACQAPALgfAXQgOgIgnAIQgnAIgRgRQgVgVg2ASQgMAVg4AFQACAbgggDQgegEgvAEQgVANgTgSQgPgPguAGQgegPg/gGQgHAUgegZQhGgEhRgEQgNgbgaAAIAAAA").cp();
		this.shape_52.setTransform(558.1,270.5);

		this.shape_53 = new cjs.Shape();
		this.shape_53.graphics.f("#339933").s().p("AJkRcQgcAEgeAAQh0AAhSg4QgKgIgKgHQgNANgPAMQhXBCh6AAQh0AAhVg+QgBABgBABQgOALgQAKQhBAnhUAAQhWAAhDgpQhXAzhuAAQiaAAhshhQhshhAAiIQAAiJBshhQAFgFAFgEQg7gXgygsQhjhZAAh+QAAh/BjhZQA3gyBDgWQg9hKAAhmQAAh8BdhYQAMgLAMgJQgbhFAAhPQAAiyCJh+QCKh+DDAAQBgAABSAfQAThFA8g2QBYhOB7AAQB8AABYBOQArAmAWAtQBFgVBPAAQDFAACLCEQCLCEAAC6QAAC2iECBQApBGAABUQAABYgrBEQAbAXAYAeQBcB0AACkQAACjhcB0QgBAAAAABQAAAAAAAAQBAANAxAtQBGA/AABZQAABZhGA/QhGA/hkAAQhAAAg1gbQgKAHgMAFQgvAXg4AIIAAAA").cp();
		this.shape_53.setTransform(534.5,115);

		this.shape_54 = new cjs.Shape();
		this.shape_54.graphics.f("#CCFF00").s().p("AACAcIgCAAQAAAAgBABQgKgCgIgHQgHgHgBgJQAAgCgBgCIABAAIgBAAQABgLAIgIQAHgHALgBQABgBAAAAIAAAAQABAAABABQALAAAHAIQAJAIAAALQgBACAAABQgBAKgHAHQgIAIgKAAIAAAA").cp();
		this.shape_54.setTransform(117,307.8);

		this.shape_55 = new cjs.Shape();
		this.shape_55.graphics.f("#FFFFFF").s().p("AgBAbQABAGgBAIQgEAUgRARQgRARgUAEQgUAEgLgLQgLgMAEgUQADgTARgRQARgRAUgEQAHgCAGABQABAJAHAHQAIAHAKACIAAAAAACAaQAKAAAIgIQAHgHABgKQAGgBAHACQATAEARARQABAAABABQAPARAEATQAEATgMAMQgKAKgUgDQgTgEgRgPQgBgBAAgBQgRgRgEgTQgBgJABgGIAAAAAgBgdQgLABgHAHQgIAIgBAMQgGAAgHgBQgTgEgQgQQgBgBgBAAQgRgRgDgUQgEgUALgLQALgLAUAEQAUADARARQAAABABABQAQAQAEATQABAGAAAGIAAAAAAdgBQAAgMgJgIQgHgIgLAAQAAgFABgGQAEgUARgRQARgRAUgEQATgDAMALQALALgEAUQgEAUgRARQgRARgTADQgIACgFgBIAAAA").cp();
		this.shape_55.setTransform(117,308);

		this.shape_56 = new cjs.Shape();
		this.shape_56.graphics.f("#CCFF00").s().p("AAWgQQAHAHAAAJQAAAKgIAIQgBACAAAAQgBABAAAAQgJAHgKAAQgIAAgIgFQgBgBgCgCIAAAAQgJgJAAgLQAAgJAHgIQABgBABgBIAAAAQABgBABgBQAIgHAJAAQALAAAJAJQABABABACIAAAA").cp();
		this.shape_56.setTransform(132.9,372.9);

		this.shape_57 = new cjs.Shape();
		this.shape_57.graphics.f("#FFFFFF").s().p("AgUASQgEAFgGADQgQALgWABQgCAAgBAAQgYAAgQgMQgRgKAAgQQAAgPARgLQAQgLAYAAQABAAACAAQAWAAAQALQAFAEAEADQgHAJAAAKQAAAKAIAIIAAAAAgQAVQAHAGAJAAQAKAAAIgHQAGAEAEAHQAMARAAAYQAAAYgMARQgLARgQAAQgOAAgLgRQgLgRAAgYQAAgYALgRQAEgFAEgFIAAAAAAVARQAHgIAAgJQAAgKgGgHQAEgFAGgEQAQgLAYAAQABAAACAAQAWAAAQALQARALAAAPQAAAPgRALQgQALgWABQgCAAgBAAQgYAAgQgMQgHgEgEgFIAAAAAAUgUQgJgJgLAAQgJAAgIAHQgEgDgDgFQgLgRAAgYQAAgYALgRQALgRAOAAQAQAAALARQAMARAAAYQAAAYgMARQgEAFgEAFIAAAA").cp();
		this.shape_57.setTransform(133,373);

		this.shape_58 = new cjs.Shape();
		this.shape_58.graphics.f("#CCFF00").s().p("AgNgYQABAAAAgBIABAAQABAAACAAQAIgEAJADQAMAFAFAKQABACAAACQADAHgDAJQgEALgJAFQgCABAAAAQgCAAAAAAQgKAFgJgEQgIgDgFgIQgCgCgBgCIAAAAIAAgBQgFgKAEgJQAEgKAJgGIAAAA").cp();
		this.shape_58.setTransform(35.9,375.8);

		this.shape_59 = new cjs.Shape();
		this.shape_59.graphics.f("#FFFFFF").s().p("AAagNQgFgKgMgFQgJgDgIAEQgDgFgBgGQgFgTAIgXQAJgXAOgLQAQgMAPAGQAPAFAFATQAFAUgIAXQgIAWgRAMQgGAEgFACIAAAAAAKAYQAEAGABAIQAGAUgJAXQgIAWgPAMQgQAMgPgFQgPgGgFgUQgEgTAIgXQAIgWAQgMQAGgEAGgCQAFAIAIADQAJAEAKgFIAAAAAgNgaQgJAGgEAKQgEAKAFAJQgGADgHACQgSAEgWgHQgBAAgBgBQgXgIgLgOQgMgQAFgPQAGgPAUgGQATgEAWAIQABAAACABQAVAIALAPQAEAGACAEIAAAAAAOAXQAJgFAEgLQADgHgDgJQAFgDAHgCQATgFAXAIQABABABAAQAVAIAMAOQALAQgFAQQgGAOgTAFQgTAEgWgGQgBgBgBAAQgWgIgMgQQgFgHgBgGIAAAA").cp();
		this.shape_59.setTransform(35.9,376);

		this.shape_60 = new cjs.Shape();
		this.shape_60.graphics.f("#CCFF00").s().p("AgIgaQABAAAAAAIABAAQABgBABAAQAJgCAJAFQAKAGADAMQABACAAACQABAHgFAJQgFAKgKADQgCAAAAABQgBAAgBAAQgJACgJgFQgJgFgDgJQgBgBgBgCIAAgCQgCgJAFgKQAGgJAKgEIAAAA").cp();
		this.shape_60.setTransform(192,411.8);

		this.shape_61 = new cjs.Shape();
		this.shape_61.graphics.f("#FFFFFF").s().p("AAJAZQAKgDAGgKQAFgJgBgHQAFgCAHgBQAUgBAUAKQABAAACABQATAMAIARQAJASgIAOQgIAOgUABQgTABgUgKQgBgBgBAAQgVgMgIgSQgEgIgBgGIAAAAAAFAaQADAHAAAIQACAUgKAVQgMAVgSAIQgTAJgNgIQgOgIgBgUQgCgUAMgUQAMgVASgJQAHgDAFgCQAEAJAIAFQAJAFAJgCIAAAAAgIgcQgKAEgGAJQgFAKADAJQgGACgHABQgUABgUgIQgBgBgBgBQgUgMgJgSQgJgSAIgOQAIgOAUgBQAUgCAVAMQABABABABQAUALAIARQADAGABAFIAAAAAAcgIQgDgMgLgGQgJgFgJACQAAgFgBgFQgBgUAKgVQAMgVASgJQASgJAOAIQAOAIABAUQABAVgMAVQgMAUgSAJQgGADgGABIAAAA").cp();
		this.shape_61.setTransform(192,412);

		this.shape_62 = new cjs.Shape();
		this.shape_62.graphics.f("#CCFF00").s().p("AgcABQAAgBABgBIAAgBQABgLAJgIQAIgGAJAAQABgBAAABIABAAQABAAABAAQALACAHAIQAIAJgBAKQAAACgBACQgCAJgIAGQgIAHgKABQAAgBgBAAQgBAAgBAAQgLgBgHgJQgGgHgBgKIAAAA").cp();
		this.shape_62.setTransform(216,294.9);

		this.shape_63 = new cjs.Shape();
		this.shape_63.graphics.f("#FFFFFF").s().p("AgbgDQgGAAgHgCQgSgGgQgQQgBgCAAAAQgQgTgBgUQgDgUAMgKQANgKATAFQATAGAQASQAAABABABQAOARABAUQAAAFAAAGQgJAAgIAHQgJAHgBAMIAAAAAgcAAQABAJAGAIQAHAIALACQABAHgDAHQgGAUgSAPQgTAQgTABQgVADgKgMQgKgMAFgUQAGgTASgQQATgPAUgCQAHAAAFAAIAAAAAAdAAQABgKgIgJQgHgIgLgBQABgFABgGQAGgTASgQQATgPAUgDQAUgBAKAMQAKAMgFATQgGAUgSAPQgTAPgTAAQgIABgFgBIAAAAAAAAbQAKAAAIgHQAIgHACgJQAGAAAGACQATAGAQASQAAABABABQAOARADAUQACATgNALQgMAKgTgFQgSgGgQgQQgBgCAAAAQgQgTAAgUQAAgIAAgGIAAAA").cp();
		this.shape_63.setTransform(216,295);

		this.shape_64 = new cjs.Shape();
		this.shape_64.graphics.f("#CCFF00").s().p("AgRgUQAAgBABgBIABAAQABgBABAAQAJgGAJACQALACAHAKQABACABABQAFAJgCAHQgCALgIAHQgBABgBAAQgBABgBABQgJAFgIgCQgKgBgHgHQgBgBgBgCIAAgBIgBAAQgGgKACgKQABgKAJgGIAAAA").cp();
		this.shape_64.setTransform(263,359.8);

		this.shape_65 = new cjs.Shape();
		this.shape_65.graphics.f("#FFFFFF").s().p("AAXgRQgHgKgLgCQgJgBgJAFQgDgEgDgGQgHgRAEgYQAEgYAOgPQAMgOAPADQAQADAJASQAIASgFAYQgEAYgOAOQgFAFgFADIAAAAAAOAXQAFAFADAHQAIATgEAYQgEAXgOAPQgMAPgQgDQgPgDgJgTQgHgSAEgXQAEgYANgPQAFgEAFgEQAHAHAKACQAIACAJgGIAAAAAgRgWQgJAHgBAKQgCAJAGAKQgFAEgGADQgSAHgWgDQgBAAgBAAQgYgEgOgOQgPgMACgQQADgQATgIQASgIAYAEQABABABAAQAWAEAOANQAEAEAEAFIAAAAAASAVQAIgHACgLQACgIgFgIQAEgEAHgDQASgIAXAFQABAAACAAQAWAEAOANQAPAMgDAQQgDAQgSAIQgSAHgWgCQgCgBgBAAQgXgEgOgOQgGgGgDgFIAAAA").cp();
		this.shape_65.setTransform(263,360);

		this.shape_66 = new cjs.Shape();
		this.shape_66.graphics.f("#CCFF00").s().p("AAcgEQAAACAAAAIAAABQAAABAAAAQAAAKgGAIQgIAJgMABQgCABAAgBQgKAAgIgGQgIgHgCgLQABgBgBgBQABgBgBgBQAAgJAHgIQAGgIAJgBQACgBACAAIACAAQAKgBAIAIQAIAGACAKIAAAA").cp();
		this.shape_66.setTransform(513.2,421);

		this.shape_67 = new cjs.Shape();
		this.shape_67.graphics.f("#FFFFFF").s().p("AgZAAQgHACgIgCQgUAAgTgPQgSgPgGgUQgFgTAKgMQAKgMAVACQATACATAPQASAPAGAUQABAGABAHQgJABgGAIQgHAIAAAJIAAAAAAegEQgBgKgJgGQgIgIgMABQAAgGAAgHQACgTAOgSQABgCAAAAQAQgTATgFQAUgGAMALQAMAKgCAUQgCAUgQASQAAABgBABQgPARgSAGQgGABgGAAIAAAAAAEAcQAMgBAIgJQAHgIAAgKQAFAAAGAAQATACATAPQASAQAGATQAFAUgKAMQgKAMgUgCQgUgCgTgQQgSgPgGgUQgBgHgBgGIAAAAAgZAEQACALAIAHQAIAGAHAAQACAHgBAGQgBAUgPASQAAABgBABQgPARgTAGQgTAFgMgKQgMgKACgUQACgTAOgSQABgCAAAAQAQgTATgFQAIgCAGAAIAAAA").cp();
		this.shape_67.setTransform(513,421);

		this.shape_68 = new cjs.Shape();
		this.shape_68.graphics.f("#CCFF00").s().p("AAFgbQABAAAAAAIABAAQACABABAAQAKAEAFAJQAGAKgDAKQgBACgBACQgDAIgJAFQgKAGgIgCQgBgBgBAAQgBAAgBAAQgKgEgGgJQgEgJABgHQAAgBAAgDIABAAIAAgBQADgLAKgGQAJgFAJACIAAAA").cp();
		this.shape_68.setTransform(328,254.9);

		this.shape_69 = new cjs.Shape();
		this.shape_69.graphics.f("#FFFFFF").s().p("AAaAKQAGAAAHADQARAJAMAVQABABABABQAKAUgBATQgBAUgOAIQgOAIgSgJQgRgIgMgTQgBgCgBgBQgKgUACgUQABgIACgGQAIACAKgGQAJgFADgIIAAAAAgbgDQgBAHAEAJQAGAJAKAEQgBAGgEAIQgIASgVAMQgVAMgUgBQgUgBgIgOQgIgOAJgSQAJgSAUgMQAVgKAUABQAHABAGABIAAAAAAFgcQgJgCgJAFQgKAGgDALQgGgBgHgDQgRgJgMgTQgBgBAAgBQgMgVACgUQABgUAOgIQAOgIASAJQASAJAMAUQAAABABACQAJAUgBASQgBAHgBAFIAAAAAAcAGQADgKgGgKQgFgJgKgEQABgEACgGQAJgSAVgMQAVgMAUABQAUACAIAOQAIAOgJARQgJATgVAMQgUAKgVgCQgHAAgFgCIAAAA").cp();
		this.shape_69.setTransform(328,255);

		this.shape_70 = new cjs.Shape();
		this.shape_70.graphics.f("#CCFF00").s().p("AAVgRQABAAABABIAAABQABABAAABQAGAJgCAIQgCAMgKAHQgCABgBABQgJAFgHgCQgLgCgHgIQgBgBAAgBQgBgBgBgBQgFgJACgJQACgJAGgGQABgCACgBIABAAIAAgBQAKgGAKACQAKABAGAJIAAAA").cp();
		this.shape_70.setTransform(373.1,421);

		this.shape_71 = new cjs.Shape();
		this.shape_71.graphics.f("#FFFFFF").s().p("AgWAOQgFAFgHADQgTAIgYgEQgXgEgPgOQgOgMACgQQADgPATgJQASgIAXAEQAYAEAPAOQAEAFAEAGQgHAGgBAJQgCAJAFAJIAAAAAAXgRQgHgJgKgBQgJgCgKAGQgEgFgCgGQgIgSADgWQAAgBAAgBQAEgYAPgOQALgPAQACQAQADAIATQAIASgEAYQAAABAAACQgFAVgNAOQgEAFgFADIAAAAAASAXQAKgHACgMQABgIgFgJQAEgDAGgDQARgIAYAEQAYAFAPAOQAOAMgDAPQgCAQgTAJQgSAIgYgFQgYgEgOgOQgFgFgDgFIAAAAAgUASQAHAIALACQAIACAIgFQAFAFACAGQAIASgEAYQAAABAAABQgFAWgNAOQgMAOgQgDQgQgCgIgSQgHgSADgWQAAgCAAgBQAEgXAPgPQAFgFAFgDIAAAA").cp();
		this.shape_71.setTransform(373,421);

		this.shape_72 = new cjs.Shape();
		this.shape_72.graphics.f("#CCFF00").s().p("AADAcQgHABgJgFQgKgFgDgKQAAgCAAAAQgBgBAAgBQgCgJAFgJQAFgJAJgDQACgBABgBIACAAQAJgCAKAFQAJAGAEAKQAAABAAAAIABABQAAABAAABQACAJgFAJQgGAKgMADQgCABgCAAIAAAA").cp();
		this.shape_72.setTransform(513.2,266);

		this.shape_73 = new cjs.Shape();
		this.shape_73.graphics.f("#FFFFFF").s().p("AAdgIQgEgKgJgGQgKgFgJACQgCgFgBgIQgBgTAJgUQAAgBABgBQAMgVASgIQASgJAOAIQAOAIACAUQABAUgMAVQgBAAAAACQgMAUgRAIQgGACgFACIAAAAAAJAcQAMgDAGgLQAFgJgCgJQAFgBAGAAQAUgCAUAKQAVANAKARQAIATgIAOQgIAOgUABQgUABgVgMQgVgMgJgSQgDgHgBgFIAAAAAgZAFQgGADgJAAQgUACgVgKQgUgMgJgSQgJgTAIgNQAIgOAUgBQAUgCAVAMQAVAMAJASQADAHABAFQgJADgFAJQgFAJACAJIAAAAAgYAJQADAKAKAGQAJAFAHgCQADAGAAAHQABAUgKAUQAAABgBABQgMAUgRAIQgSAJgOgIQgNgIgCgUQgBgTAKgUQABgCAAAAQAMgVATgJQAHgDAGgBIAAAA").cp();
		this.shape_73.setTransform(513,266);

		this.shape_74 = new cjs.Shape();
		this.shape_74.graphics.f("#CCFF00").s().p("AAOgXQABAAABAAIAAABQACABAAABQAJAGABALQACAJgHAKQgBACgBABQgHAIgJABQgJACgJgFQgBgBgBgBQgBAAgBgBQgIgHgCgKQgCgIAEgIQABgCABgBIABgBIAAgBQAHgJAMgCQAIgCAJAGIAAAA").cp();
		this.shape_74.setTransform(341,343.9);

		this.shape_75 = new cjs.Shape();
		this.shape_75.graphics.f("#FFFFFF").s().p("AAWASQAGADAEAFQANAPAFAXQAAABAAACQADAWgHARQgIATgQADQgPACgNgOQgNgOgEgWQgBgCAAgBQgEgXAIgSQADgHAFgFQAJAFAJgCQAJgBAHgIIAAAAAAPgYQgJgGgIACQgMACgHAJQgFgDgFgFQgNgOgFgWQAAgBAAgBQgEgYAIgSQAIgTAQgDQAPgDANAPQANAPAEAYQABABAAABQADAWgHARQgDAGgDAFIAAAAAAYAPQAHgKgCgJQgBgLgJgGQADgEAEgFQAPgNAXgEQAYgFASAIQATAJADAPQADAQgPAMQgPAOgYAEQgXAEgSgIQgHgDgFgEIAAAAAgYgMQgEAIACAIQACAKAIAHQgDAGgGAGQgPAOgXAEQgYAEgSgIQgSgIgDgQQgDgPAOgNQAPgNAYgEQAXgEATAHQAGADAEAEIAAAA").cp();
		this.shape_75.setTransform(340.9,344);

		this.shape_76 = new cjs.Shape();
		this.shape_76.graphics.f("#CCFF00").s().p("AAYAPQgFAIgKAEQgJAEgJgEQgBgBgBAAQgBgBgBAAQgJgFgEgLQgDgIADgHQAAgCABgCIAAgBIAAAAQAGgLALgEQAIgDAJAEQACAAAAAAIABAAQABABABABQAJAFADAJQAFAKgFALQgBACgBABIAAAA").cp();
		this.shape_76.setTransform(413.1,272.9);

		this.shape_77 = new cjs.Shape();
		this.shape_77.graphics.f("#FFFFFF").s().p("AAKgaQgKgEgIADQgLAEgFALQgGgDgFgEQgPgLgJgVQgBgBAAgBQgIgXAEgTQAFgUAPgGQAPgFARAMQAPAMAHAWQABABAAACQAHAVgEASQgBAHgDAFIAAAAAAaALQAFgLgEgKQgEgJgIgFQABgFAEgFQALgQAXgIQAXgIATAFQAUAEAFAPQAGAPgMARQgMAOgXAJQgWAIgUgGQgHgBgFgDIAAAAAgMAYQgCAHgFAGQgMARgXAIQgWAIgTgFQgUgFgFgPQgGgPAMgQQALgOAXgIQAWgJAUAFQAHACAGADQgEAHAEAIQADALAKAFIAAAAAgJAaQAJAEAKgEQAKgEAFgIQAFACAGAEQAQAMAIAXQAAABABABQAHAVgFATQgEATgQAGQgOAFgRgLQgNgMgJgVQAAgBAAgBQgJgWAFgUQACgIADgFIAAAA").cp();
		this.shape_77.setTransform(413.1,273);

		this.shape_78 = new cjs.Shape();
		this.shape_78.graphics.f("#CCFF00").s().p("AAZgNQAAABABAAIAAABQAAABAAACQAEAIgDAJQgFAMgKAFQgCABgCAAQgIADgIgDQgLgEgFgJQgBgCAAAAQAAgCAAAAQgFgKAEgJQADgIAIgFQACgCACgBIAAAAIABAAQAKgFAJAEQAKAEAGAJIAAAA").cp();
		this.shape_78.setTransform(448,355.5);

		this.shape_79 = new cjs.Shape();
		this.shape_79.graphics.f("#FFFFFF").s().p("AgIgZQgDgGgCgHQgEgSAHgWQAAgBABgBQAIgXAOgLQAQgMAPAFQAPAGAGAUQAEATgIAWQAAABgBACQgIAVgPALQgGAEgEACQgGgJgKgEQgLgEgIAFIAAAAAAOAaQAKgFAFgMQADgJgEgIQAFgDAGgBQATgFAXAIQAXAJALAOQAMAQgGAPQgFAPgTAFQgUAFgXgIQgWgIgMgRQgEgGgCgFIAAAAAAKAbQADAFACAHQAFATgIAXQgBABAAABQgIAVgOAMQgQALgQgFQgOgGgFgTQgEgTAGgWQABgBAAgBQAIgWAQgMQAHgFAGgBQAFAJALAEQAHADAJgDIAAAAAgNgWQgIAFgDAIQgEAJAFAKQgGAEgIABQgUAGgXgJQgWgIgMgPQgMgQAFgPQAGgPAUgFQATgEAXAIQAWAIAMAQQAEAGACAGIAAAA").cp();
		this.shape_79.setTransform(447.8,355.5);

		this.shape_80 = new cjs.Shape();
		this.shape_80.graphics.f().s("#33CC00").ss(1,1,1).p("EAq3gKcIAAhkEgq1AMBIgBhyEAqugKcUg6agANgbJAWq");
		this.shape_80.setTransform(274.4,288.9);

		this.shape_81 = new cjs.Shape();
		this.shape_81.graphics.f("#33CC00").s().p("Egq1AEgUAbJgWqA6aAAOIAJAAMAAAAj5MhVjAAAIgKtcQABAAAAgBIAAAA").cp();
		this.shape_81.setTransform(274.4,336.9);

		this.shape_82 = new cjs.Shape();
		this.shape_82.graphics.f("#FF0000").s().p("AgFgLIABAAQAAAAABgBQADgBAEABQAGADACAFQABABAAAAQACADgCAEQgCAFgFADQAAABgBAAQAAAAgBAAQgEACgDgCQgFgCgCgDQgBgBAAgBQAAAAgBgBQgCgFACgDQACgFAFgDIAAAA").cp();
		this.shape_82.setTransform(90.4,189.7);

		this.shape_83 = new cjs.Shape();
		this.shape_83.graphics.f("#0000FF").s().p("AAMgFQgCgFgGgDQgEgBgDABQgBgCgBgCQgDgKAEgLQAEgLAHgGQAIgGAHADQAHACADAKQACAKgEALQgEALgIAGQgDACgDABIAAAAAANgEQACgBAEgBQAJgCALAEQABAAABAAQAKAEAFAGQAGAIgDAHQgCAHgKADQgJACgKgDQgBgBgBAAQgLgEgFgIQgDgDgBgDQAFgDACgFQACgDgCgEIAAAAAgFgMQgFADgCAFQgCAEACAEQgCACgDABQgKACgKgEQgBAAAAAAQgLgEgGgGQgGgIADgHQACgIAKgCQAKgDALAEQAAABABAAQAKAEAGAHQABADACACIAAAAAgKAHQACADAFACQADACAEgCQACADABAEQADAJgEAMQgEALgGAFQgJAGgHgDQgHgCgCgKQgDgJAEgLQAEgMAIgFQADgDADAAIAAAA").cp();
		this.shape_83.setTransform(90.4,189.8);

		this.shape_84 = new cjs.Shape();
		this.shape_84.graphics.f("#FF0000").s().p("AgHgKQABgBABAAQAAAAABgBQAEgCAEACQAFACADAFIAAABQAAAAABABQABADgBAEQgDAGgFACQgBABAAAAQgEACgDgCQgFgCgDgFQgBAAAAgBQAAAAAAgBQgCgEACgDQACgFADgCIAAAA").cp();
		this.shape_84.setTransform(22.8,296);

		this.shape_85 = new cjs.Shape();
		this.shape_85.graphics.f("#0000FF").s().p("AgDgMQgCgCgBgDQgCgKAEgKQAAgBAAAAQAEgLAGgGQAIgGAHADQAIACACAKQADAKgEALQgBAAAAABQgEAKgHAGQgDABgCACQgDgFgFgCQgFgCgDACIAAAAAgGgKQgDACgCAFQgCADACAEQgDACgEABQgJADgMgEQgLgEgFgGQgGgJADgHQACgHAKgCQAJgDALAEQAMAEAFAIQADADAAADIAAAAAAGAMQAFgCADgGQABgEgBgDQACgBACgBQAKgDALAEQALAEAGAHQAGAIgDAHQgCAHgKADQgKACgLgEQgLgEgGgIQgCgDgBgDIAAAAAgKAGQADAFAFACQACACAFgCQABACABAEQACAJgEALQAAABAAABQgEAKgGAFQgIAGgHgDQgHgCgDgKQgCgJADgKQABgBAAgBQAEgLAIgFQADgDADgBIAAAA").cp();
		this.shape_85.setTransform(22.7,296);

		this.shape_86 = new cjs.Shape();
		this.shape_86.graphics.f("#FF0000").s().p("AAKgIQABABAAAAIAAAAQAAABABAAQACAFgBADQgBAGgFADQAAAAgBABQgEACgDAAQgFgBgEgFQAAAAAAgBQAAAAgBgBQgDgEABgDQABgFAEgDQAAAAABgBIAAAAIABgBQAFgDADACQAFABADADIAAAA").cp();
		this.shape_86.setTransform(110.5,287.5);

		this.shape_87 = new cjs.Shape();
		this.shape_87.graphics.f("#0000FF").s().p("AgGgLQgCgCgBgDQgEgJACgKQAAgBAAgBQACgLAHgHQAFgHAHABQAIABAEAJQAEAJgCAMQAAAAAAABQgCALgHAHQgCACgCABQgDgDgFgBQgEgCgFADIAAAAAAIALQAFgDABgGQABgDgDgFQACgBADgBQAJgEALACQAMACAHAHQAHAFgBAHQgBAIgJAEQgKAEgLgCQgMgCgHgHQgCgCgCgDIAAAAAAHAMQACACABADQAEAJgCAMQgBAAAAABQgCALgGAHQgFAHgIgCQgHgBgEgJQgEgJABgKQAAgBABgBQACgLAGgHQADgDADgCQADAFAGABQACAAAFgCIAAAAAgIgJQgDADgBAFQgBADADAEQgCADgEACQgKAEgLgCQgMgCgHgHQgHgFACgIQABgIAJgEQAJgEALACQAMACAHAHQADADABACIAAAA").cp();
		this.shape_87.setTransform(110.5,287.5);

		this.shape_88 = new cjs.Shape();
		this.shape_88.graphics.f("#FF0000").s().p("AgBgNQABAAAAAAIAAAAQAAAAAAAAQAFAAAEAEQAEAEABAFQAAAAAAAAQAAAFgDADQgEAEgFACQAAgBgBABQgBgBAAABQgDAAgEgEQgEgDgBgEQAAgBAAgBQAAgBAAAAQgBgEAEgEQADgEAFgBIAAAA").cp();
		this.shape_88.setTransform(215.4,222.7);

		this.shape_89 = new cjs.Shape();
		this.shape_89.graphics.f("#0000FF").s().p("AAAANQAAACAAAFQAAAKgHAJQgHAJgKACQgKADgFgFQgGgFABgKQABgJAHgJQAIgJAJgDQAEgBACAAQABAEAEADQAEAEAEAAIAAAAAACANQAFgCADgEQADgDAAgEQADAAAEAAQAKAAAJAHQAAABABAAQAHAIAEAIQACAKgFAGQgFAGgKgBQgKgBgIgHQAAAAgBgBQgJgHgCgJQgCgFABgCIAAAAAgBgOQgFABgEAEQgDAEAAAFQgDAAgDAAQgKAAgIgHQgBAAAAAAQgJgIgDgJQgDgKAFgGQAGgGAKABQAJABAJAIQABAAAAAAQAIAIADAJQABADAAACIAAAAAANgBQAAgFgFgEQgEgEgEAAQAAgCAAgDQABgKAHgJQAIgJAJgDQAKgCAGAFQAFAFAAAJQgBALgIAJQgHAJgKACQgEABgDAAIAAAA").cp();
		this.shape_89.setTransform(215.5,222.8);

		this.shape_90 = new cjs.Shape();
		this.shape_90.graphics.f("#FF0000").s().p("AAFgMIABABIAAAAQAAAAABAAQAEACACAFQACAEgDAGQAAAAAAABQgDAEgEACQgFACgDgCQgBAAgBAAQAAgBAAAAQgFgDgCgFQgBgEABgDQAAgBABAAQAAgBAAAAQADgFAFgBQADgDAFACIAAAA").cp();
		this.shape_90.setTransform(13.5,249);

		this.shape_91 = new cjs.Shape();
		this.shape_91.graphics.f("#0000FF").s().p("AgLgGQgDAAgDgCQgHgGgEgKQAAgBgBAAQgEgLADgKQACgKAHgCQAIgDAIAGQAGAGAEALQAAAAAAABQAEAKgCAKQgBACgBADQgFgCgDACQgFABgDAFIAAAAAAMAFQADgFgCgEQgCgFgEgCQABgCABgCQAGgJALgEQALgEAKADQAKACACAHQADAHgGAJQgGAGgLAEQgLAEgKgCQgDgCgDgBIAAAAAgFALQgBADgDAEQgFAIgMAEQgLAEgJgCQgKgDgCgHQgDgHAGgIQAFgHALgEQAMgEAJADQAEABACABQgBADABAEQACAFAFACIAAAAAgDAMQADACAFgBQAEgCADgEQACAAADADQAIAFAEALQAAABABABQADAKgCAJQgDAKgHACQgHADgIgGQgGgFgEgKQAAgBAAgBQgEgLACgJQABgEACgDIAAAA").cp();
		this.shape_91.setTransform(13.5,249);

		this.shape_92 = new cjs.Shape();
		this.shape_92.graphics.f("#FF0000").s().p("AgDgMQAAAAABAAIAAAAQABAAAAgBQADgBAFADQAFADABAGQAAAAABACQABACgDAFQgDAEgFACQAAAAAAAAQgBAAgBAAQgDACgFgDQgEgDgBgEQgBgBAAAAIAAgBQAAAAAAAAQgCgEAEgFQACgEAFgCIAAAA").cp();
		this.shape_92.setTransform(133.2,202.4);

		this.shape_93 = new cjs.Shape();
		this.shape_93.graphics.f("#0000FF").s().p("AANgDQgBgGgFgDQgFgDgDABQgBgCAAgDQAAgKADgKQAGgKAKgEQAJgEAGADQAHAEABAKQAAAKgGAKQgFAKgKAFQgDABgDABIAAAAAAOgBQADgCADAAQAKgBAKAEQAAABABAAQAJAGAFAIQAEAJgEAHQgEAGgKABQgKABgJgFQgBAAAAgBQgKgGgEgJQgCgDgBgDQAFgCADgEQADgFgBgCIAAAAAgDgNQgFACgCAEQgEAFACAEQgDAAgDABQgKAAgKgDQAAAAgBAAQgKgGgEgJQgFgJAEgHQAEgHALgBQAJAAAKAGQABAAAAAAQAKAGAEAIQABADABADIAAAAAgLAEQABAEAEADQAFADADgCQACADAAAFQABAJgFALQgFAKgJAEQgJAEgHgEQgGgDgBgKQgBgKAGgKQAGgLAJgEQADgBADgBIAAAA").cp();
		this.shape_93.setTransform(133.2,202.5);

		this.shape_94 = new cjs.Shape();
		this.shape_94.graphics.f("#FF0000").s().p("AgIgJQABgBAAAAIAAAAQABAAAAgBQAFgCADABQAGABADAFQAAAAABABQACAEAAADQgBAFgFAEQAAAAgBAAQAAAAgBABQgEADgDgBQgFgBgDgEQAAAAgBgBIAAAAIgBgBQgDgFACgDQABgFADgDIAAAA").cp();
		this.shape_94.setTransform(45.4,203.4);

		this.shape_95 = new cjs.Shape();
		this.shape_95.graphics.f("#0000FF").s().p("AALgHQgDgFgGgBQgDgBgFADQgBgCgBgDQgEgJACgLQACgMAHgHQAFgHAHABQAIABAEAJQAEAKgCALQgCAMgHAHQgCACgDACIAAAAAAGALQADACACAEQAEAKgCALQgCAMgHAHQgFAHgIgCQgIgBgEgJQgEgJACgLQACgMAHgHQADgDACgBQADADAFABQADABAEgDIAAAAAgIgKQgDADgBAFQgCAEADAFQgCACgDABQgJAEgKgCQgBAAgBAAQgLgCgHgHQgHgFABgHQABgIAJgEQAJgEAMACQAAAAABAAQALACAHAHQACACABACIAAAAAAIAKQAFgDABgGQAAgCgCgFQACgCADgBQAJgEAMACQAAABABAAQALACAHAGQAHAFgCAIQgBAHgJAEQgJAEgKgBQgBAAgBgBQgLgCgHgGQgDgDgCgDIAAAA").cp();
		this.shape_95.setTransform(45.4,203.5);

		this.shape_96 = new cjs.Shape();
		this.shape_96.graphics.f("#FF0000").s().p("AALAJQgEAEgEABQgEABgEgDQgBAAAAgBQgBAAAAgBQgEgDgBgFQgBgDACgEQABAAAAgBIABAAIgBgBQAEgFAGAAQADgCAEADQAAABABAAIAAAAQABABAAAAQAEADABAFQABAEgDAFQgBAAAAABIAAAA").cp();
		this.shape_96.setTransform(53.4,254);

		this.shape_97 = new cjs.Shape();
		this.shape_97.graphics.f("#0000FF").s().p("AAMAHQADgFgBgEQgBgFgEgDQABgCADgCQAHgHALgCQAMgCAJAEQAJAEABAHQACAIgHAFQgIAHgLACQgMACgJgEQgDgBgCgCIAAAAAgHAJQgBAEgDADQgIAHgLACQgMACgJgEQgJgEgBgIQgBgIAHgFQAHgHALgCQAMgCAJAEQADACACABQgCAEABADQABAFAEADIAAAAAgFALQAEADAEgBQAEgBAEgEQACACADACQAGAHACAMQAAAAAAABQACALgEAJQgEAJgIABQgHABgFgHQgGgHgDgKQAAgBAAgBQgCgLAEgJQABgEADgCIAAAAAAHgMQgEgCgDABQgGAAgEAFQgCgCgCgCQgHgHgCgKQAAgBAAgBQgCgLAEgJQAEgJAHgBQAIgCAFAHQAHAHACAMQAAAAAAABQACALgEAJQgBACgCACIAAAA").cp();
		this.shape_97.setTransform(53.4,254);

		this.shape_98 = new cjs.Shape();
		this.shape_98.graphics.f("#FF0000").s().p("AgNAAQABgGAFgDQAEgEADAAQAAABABgBIAAABQABgBAAABQAFABADAEQAEAEAAAEQgBABAAABQgBAFgDADQgEADgFAAQAAAAAAAAQAAgBgBABQgFgBgDgEQgDgEgBgEQAAgBAAAAQABAAgBAAIAAAA").cp();
		this.shape_98.setTransform(103.9,235.5);

		this.shape_99 = new cjs.Shape();
		this.shape_99.graphics.f("#0000FF").s().p("AgBANQABADgCAEQgCAKgJAIQgJAHgKABQgKABgFgGQgFgGADgKQACgJAJgHQAJgIAKgBQADAAADAAQABAEADAEQADAEAFABIAAAAAAAANQAFAAAEgDQADgDABgFQADAAAEABQAJACAIAJQAAABABAAQAGAJACAJQAAAKgGAFQgGAFgJgCQgJgDgHgIQgBgBAAAAQgIgJAAgKQAAgEAAgDIAAAAAAAgOQgDAAgEAEQgFADgBAGQgCAAgEgBQgJgCgHgJQgBAAAAgBQgHgJgCgJQAAgKAGgFQAGgGAJADQAKADAHAJQAAAAABABQAGAJAAAJQAAADAAACIAAAAAAOAAQAAgEgEgEQgDgEgFgBQAAgDABgCQADgKAJgHQAJgIAKgBQAJgBAFAGQAFAGgCAJQgDAKgJAIQgJAGgKAAQgDABgDgBIAAAA").cp();
		this.shape_99.setTransform(103.9,235.5);

		this.shape_100 = new cjs.Shape();
		this.shape_100.graphics.f("#FF0000").s().p("AACgMIABAAIAAAAQABAAAAAAQAFACADAFQADAFgCADQAAABAAABQgCAEgEADQgFACgDAAIgBgBQgBAAAAAAQgFgCgDgEQgCgFAAgCQAAgBABgBIAAAAIAAgBQACgFAFgDQAEgCADABIAAAA").cp();
		this.shape_100.setTransform(156,257);

		this.shape_101 = new cjs.Shape();
		this.shape_101.graphics.f("#0000FF").s().p("AANAEQADABADABQAIAFAGAKQAAAAABABQAFAKAAAJQgBAKgHAEQgHADgIgEQgJgEgGgJQAAgBAAAAQgEgKABgKQAAgEABgDQADABAFgDQAEgCACgFIAAAAAACgNQgDgBgEADQgFACgCAGQgDgBgDgBQgJgEgFgKQgBAAAAgBQgGgKABgKQAAgKAHgEQAHgEAJAFQAJAEAGAKQAAABAAAAQAEAKgBAJQAAADgBADIAAAAAANADQACgEgDgFQgDgFgFgBQABgDABgCQAFgJAKgGQAKgGAKABQAKABAEAHQADAGgEAJQgEAJgKAFQgLAFgJgBQgEAAgDgBIAAAAAgNAAQAAACACAEQADAFAFABQgBAEgBADQgFAJgKAGQgKAGgKgBQgKAAgEgHQgEgHAFgJQAEgIAKgGQAKgEAKAAQAEABACABIAAAA").cp();
		this.shape_101.setTransform(156,257);

		this.shape_102 = new cjs.Shape();
		this.shape_102.graphics.f().s("#339900").ss(1,1,1).p("EgmdgTDIAAAMQXjkjTtKcQJ4FOIZIIQI2InGkLRMhM7AAAMAAAgnH");
		this.shape_102.setTransform(246.6,312.5);

		this.shape_103 = new cjs.Shape();
		this.shape_103.graphics.f("#339900").s().p("EgmdgS3QXjkjTtKcQJ4FOIZIIQI2InGkLRMhM7AAAMAAAgnH").cp();
		this.shape_103.setTransform(246.6,312.5);

		this.shape_104 = new cjs.Shape();
		this.shape_104.graphics.f("#33CCFF").s().p("EAq+AfQMhV7AAAMAAAg+fMBV7AAAMAAAA+f").cp();
		this.shape_104.setTransform(275,200);

		this.addChild(this.shape_104,this.shape_103,this.shape_102,this.shape_101,this.shape_100,this.shape_99,this.shape_98,this.shape_97,this.shape_96,this.shape_95,this.shape_94,this.shape_93,this.shape_92,this.shape_91,this.shape_90,this.shape_89,this.shape_88,this.shape_87,this.shape_86,this.shape_85,this.shape_84,this.shape_83,this.shape_82,this.shape_81,this.shape_80,this.shape_79,this.shape_78,this.shape_77,this.shape_76,this.shape_75,this.shape_74,this.shape_73,this.shape_72,this.shape_71,this.shape_70,this.shape_69,this.shape_68,this.shape_67,this.shape_66,this.shape_65,this.shape_64,this.shape_63,this.shape_62,this.shape_61,this.shape_60,this.shape_59,this.shape_58,this.shape_57,this.shape_56,this.shape_55,this.shape_54,this.shape_53,this.shape_52,this.shape_51);
	}).prototype = p = new cjs.Container();
	p.nominalBounds = new cjs.Rectangle(0,0,644,451.9);


	(lib.border_mc = function() {
		this.initialize();

		// Layer 1
		this.shape_105 = new cjs.Shape();
		this.shape_105.graphics.f().s("#00CCFF").ss(1,1,1).p("AAFAFIgJAAIAAgJIAJAAIAAAJ").cp();

		this.addChild(this.shape_105);
	}).prototype = p = new cjs.Container();
	p.nominalBounds = new cjs.Rectangle(-0.4,-0.4,1,1);


	(lib.border_box = function() {
		this.initialize();

		// Layer 1
		this.shape_106 = new cjs.Shape();
		this.shape_106.graphics.f("rgba(255,0,0,0)").s().p("AB9hkIj5AAIAADJID5AAIAAjJ").cp();

		this.addChild(this.shape_106);
	}).prototype = p = new cjs.Container();
	p.nominalBounds = new cjs.Rectangle(-12.4,-10.1,25,20.4);

	(lib.Ladybird = function(mode,startPosition,loop) {
		this.initialize(mode,startPosition,loop,{},true);

		// Layer 2
		this.instance_1 = new lib.LadybirdWing2();
		this.instance_1.setTransform(5.5,10,0.099,0.099,0,-174.3,5.6,34,76.8);

		this.timeline.addTween(cjs.Tween.get(this.instance_1).to({regX:33.9,regY:76.7,scaleY:0.1,skewX:-163.5,skewY:16.3},2).to({regX:34,regY:76.8,scaleY:0.1,skewX:-174.2,skewY:5.6},2).wait(1));

		// wing
		this.instance_2 = new lib.LadybirdWing1();
		this.instance_2.setTransform(11.5,4.4,0.099,0.1,91.3,0,0,21.9,70);

		this.timeline.addTween(cjs.Tween.get(this.instance_2).to({regY:70.2,rotation:81.3},2).to({regY:70,rotation:91.3},2).wait(1));

		// leg
		this.instance_3 = new lib.LadybirdBody();
		this.instance_3.setTransform(10.2,9.5,0.1,0.1,90,0,0,96,94.5);

		this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_3}]}).wait(5));

	}).prototype = p = new cjs.MovieClip();
	p.nominalBounds = new cjs.Rectangle(0.8,0,18.9,19.3);


	(lib.Fly = function(mode,startPosition,loop) {
		this.initialize(mode,startPosition,loop,{},true);

		// fly
		this.instance_4 = new lib.FlyBody();
		this.instance_4.setTransform(5.8,5.6,0.5,0.5,0,0,0,5.5,8.2);

		this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_4}]}).wait(4));

		// wing
		this.instance_5 = new lib.FlyWing("synched",0);
		this.instance_5.setTransform(4,3.6,0.135,0.141,-149,0,0,2.1,10.3);

		this.timeline.addTween(cjs.Tween.get(this.instance_5).to({regX:1.9,regY:10.1,scaleX:0.08,rotation:0,skewX:-148.9,skewY:-122.4,x:4.2,y:3.5},2).to({regX:2.1,regY:9.9,scaleX:0.11,skewX:-149,skewY:-135.7,y:3.8},1).wait(1));

		// wing
		this.instance_6 = new lib.FlyWing("synched",0);
		this.instance_6.setTransform(7.7,3.9,0.123,0.128,-5.7,0,0,0.7,13.4);

		this.timeline.addTween(cjs.Tween.get(this.instance_6).to({regX:0.6,regY:13.1,scaleX:0.07,rotation:0,skewX:-5.6,skewY:-36.8,x:7.9,y:3.8},2).to({regX:1.4,regY:13.3,scaleX:0.1,skewY:-21.1,y:4.1},1).wait(1));

	}).prototype = p = new cjs.MovieClip();
	p.nominalBounds = new cjs.Rectangle(0,0.1,11.5,9.5);


	(lib.Bee = function(mode,startPosition,loop) {
		this.initialize(mode,startPosition,loop,{},true);

		// BeeSingleWing
		this.instance_7 = new lib.BeeSingleWing();
		this.instance_7.setTransform(4.5,8.2,0.194,0.194,-82.2);

		this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(1).to({rotation:-30.8,x:3.8,y:4.6},0).wait(1));

		// BeeSingleWing
		this.instance_8 = new lib.BeeSingleWing();
		this.instance_8.setTransform(3.8,6.5,0.194,0.194,-53.4);

		this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(1).to({rotation:-1.9,x:4.7,y:3},0).wait(1));

		// BeeBody
		this.instance_9 = new lib.BeeBody("synched",0);
		this.instance_9.setTransform(6.6,9.6,0.2,0.2);

		this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_9}]}).wait(2));

		// BeeSingleWing
		this.instance_10 = new lib.BeeSingleWing();
		this.instance_10.setTransform(12.6,6,0.193,0.193,148.7);

		this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(1).to({rotation:94.4,x:11.4,y:2.4},0).wait(1));

		// BeeSingleWing
		this.instance_11 = new lib.BeeSingleWing();
		this.instance_11.setTransform(11.6,7.7,0.193,0.193,177.5);

		this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(1).to({rotation:123.2,x:12.2,y:4.2},0).wait(1));

	}).prototype = p = new cjs.MovieClip();
	p.nominalBounds = new cjs.Rectangle(0.1,2.4,16.2,12.5);


	(lib.LadybirdAnim = function(mode,startPosition,loop) {
		this.initialize(mode,startPosition,loop,{start:0,stop:29,payoff_side:30,payoff_up:55,fly_away:80,go_away:119,go_away_bad:120},true);

		// timeline functions:
		this.frame_29 = function() {
			this.stop();
		}
		this.frame_30 = function() {
			if(this.first) whizz.playSound("buzz");
		}
		this.frame_54 = function() {
			if(this.first) whizz.stopSound("buzz");
		}
		this.frame_55 = function() {
			if(this.first) whizz.playSound("buzz");
		}
		this.frame_79 = function() {
			this.stop();
			if(this.first) this.parent.parent.gameState = 'waiting';
			if(this.first) whizz.myManager.hideOK(false);
			if(this.first) whizz.stopSound("buzz");
		}
		this.frame_80 = function() {
			if(this.first) whizz.playSound("buzz");
		}
		this.frame_118 = function() {
			if(this.first) this.parent.parent.clearGraphic();
			this.stop();
			if(this.first) whizz.stopSound("buzz");
		}
		this.frame_119 = function() {
			this.stop();
			if(this.first) this.parent.parent.gameState = 'waiting_bad';
			if(this.first) whizz.myManager.hideOK(false);
		}
		this.frame_120 = function() {
			//this.parent.parent.forDraw.graphics.clear();
		}
		this.frame_157 = function() {
			if(this.first) this.parent.parent.clearGraphic();
		}

		// actions tween:
		this.timeline.addTween(cjs.Tween.get(this).wait(29).call(this.frame_29).wait(1).call(this.frame_30).wait(24).call(this.frame_54).wait(1).call(this.frame_55).wait(24).call(this.frame_79).wait(1).call(this.frame_80).wait(38).call(this.frame_118).wait(1).call(this.frame_119).wait(1).call(this.frame_120).wait(37).call(this.frame_157));

		// Layer 1

		var b = new cjs.SpriteSheetBuilder();
		b.addMovieClip(new lib.Ladybird(), null, whizz.scale);
		this.ladybird = new cjs.BitmapAnimation(b.build());
		this.ladybird.setTransform(-178.8,364.4,1/whizz.scale,1/whizz.scale);
		this.ladybird.play();
		this.timeline.addTween(cjs.Tween.get(this.ladybird).to({x:-29.2,y:281},4).wait(5).to({x:-114.7,y:199.4},5).to({x:16.1,y:129.4},5).to({x:-52.2,y:36.4},5).to({x:-8.6,y:-10.6},5).to({x:-8.2,y:-11.5},1).to({x:-1.3,y:-10.5},2).to({x:-15.1,y:-11.1},2).to({x:-8.2,y:-10.9},2).to({x:-1.1,y:-10.7},2).to({x:-15.2,y:-11.1},2).to({x:-8.2,y:-10.9},2).to({x:-1.2,y:-10.6},2).to({x:-15.2,y:-11.1},2).to({x:-8.2,y:-10.9},2).to({x:-1.2,y:-10.6},2).to({x:-15.2,y:-11.1},2).to({x:-8.2,y:-10.9},2).wait(1).to({y:-18},2).to({x:-8.4,y:-4.1},2).to({x:-8.2,y:-10.9},2).to({y:-17.6},2).to({x:-8.4,y:-4.1},2).to({x:-8.2,y:-10.9},2).to({y:-17.6},2).to({x:-8.4,y:-4.1},2).to({x:-8.2,y:-10.9},2).to({y:-17.6},2).to({x:-8.4,y:-4.1},2).to({x:-8.2,y:-10.9},2).wait(1).to({x:196.1,y:181.8},18).to({x:535.8,y:131.8},20).to({x:-8.2,y:-10.9},1).wait(1).to({x:6,y:-10.1},0).to({x:535.8,y:20.7},37).wait(1));


		// borderBox
		this.borderBox = new lib.border_box();
		this.borderBox.setTransform(1,-1.6,1.096,1.233);

		this.timeline.addTween(cjs.Tween.get(this.borderBox).to({_off:true},30).wait(128));

		// bg
		this.shape_107 = new cjs.Shape();
		this.shape_107.graphics.f("rgba(255,0,0,0)").s().p("ACJh8IkRAAIAAD5IERAAIAAj5").cp();
		this.shape_107.setTransform(1.1,-1.7,1,1,0,0,0,0,-0.2);

		this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_107}]}).to({state:[]},30).to({state:[]},25).wait(103));

	}).prototype = p = new cjs.MovieClip();
	p.nominalBounds = new cjs.Rectangle(-180.1,-14.1,194.9,397);


	(lib.FlyAnim = function(mode,startPosition,loop) {
		this.initialize(mode,startPosition,loop,{start:0,stop:29,payoff_side:30,payoff_up:55,fly_away:80,go_away:119,go_away_bad:120},true);

		// timeline functions:
		this.frame_29 = function() {
			this.stop();
		}
		this.frame_30 = function() {
			if(this.first) whizz.playSound("beeswarm");
		}
		this.frame_54 = function() {
			if(this.first) whizz.stopSound("beeswarm");
		}
		this.frame_55 = function() {
			if(this.first) whizz.playSound("beeswarm");
		}
		this.frame_79 = function() {
			this.stop();
			// TODO: sprawdzic
			this.parent.parent.gameState = 'waiting';
			if(this.first) whizz.myManager.hideOK(false);
			if(this.first) whizz.stopSound("beeswarm");
		}
		this.frame_80 = function() {
			if(this.first) whizz.playSound("beeswarm");
		}
		this.frame_117 = function() {
			if(this.first) whizz.stopSound("beeswarm");
		}
		this.frame_118 = function() {
			if(this.first)  this.parent.parent.clearGraphic();
			if(this.first) whizz.stopSound("beeswarm");
			this.stop();
		}
		this.frame_119 = function() {
			this.stop();
			if(this.first) this.parent.parent.gameState = 'waiting_bad';
			if(this.first) whizz.myManager.hideOK(false);
		}
		this.frame_120 = function() {
			//this.parent.parent.forDraw.graphics.clear();
		}
		this.frame_157 = function() {
			if(this.first) this.parent.parent.clearGraphic();
		}

		// actions tween:
		this.timeline.addTween(cjs.Tween.get(this).wait(29).call(this.frame_29).wait(1).call(this.frame_30).wait(24).call(this.frame_54).wait(1).call(this.frame_55).wait(24).call(this.frame_79).wait(1).call(this.frame_80).wait(37).call(this.frame_117).wait(1).call(this.frame_118).wait(1).call(this.frame_119).wait(1).call(this.frame_120).wait(37).call(this.frame_157));

		// Layer 1





		var b = new cjs.SpriteSheetBuilder();
		b.addMovieClip(new lib.Fly(), null, whizz.scale);
		this.fly = new cjs.BitmapAnimation(b.build());

		this.fly.setTransform(-67.6,175.2,1/whizz.scale,1/whizz.scale,0,0,0);
		this.fly.play();

		this.timeline.addTween(cjs.Tween.get(this.fly).to({x:-85.5,y:122.2},4).to({x:-16.6,y:112.2},5).to({x:-41.6,y:58.1},5).to({x:18.2,y:40.1},5).to({x:-36.5,y:2.1},5).to({x:-5.6,y:-4.8},5).to({x:1.2},1).to({x:-12.6},2).to({x:-5.6},2).to({x:1.2},2).to({x:-12.6},2).to({x:-5.6},2).to({x:1.2},2).to({x:-12.6},2).to({x:-5.6},2).to({x:1.2},2).to({x:-12.6},2).to({x:-5.6},2).wait(3).to({y:-11.8},2).to({y:2.1},2).to({y:-4.8},2).to({y:-11.8},2).to({y:2.1},2).to({y:-4.8},2).to({y:-11.8},2).to({y:2.1},2).to({y:-4.8},2).to({y:-11.8},2).to({y:2.1},2).to({y:-4.8},2).wait(1).to({x:194.4,y:181.6},18).to({x:534.4,y:131.5},20).to({x:-5.6,y:-4.8},1).wait(1).to({x:8.4,y:-4.1},0).to({x:534.4,y:20.6},37).wait(1));


		// bg
		this.borderBox = new lib.border_box();
		this.borderBox.setTransform(0,0,0.699,0.688);

		this.shape_84 = new cjs.Shape();
		this.shape_84.graphics.f("rgba(255,0,0,0)").s().p("ABXhFIitAAIAACLICtAAIAAiL").cp();

		this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_84},{t:this.borderBox}]}).to({state:[{t:this.shape_84},{t:this.borderBox}]},29).to({state:[]},1).to({state:[]},25).wait(103));


	}).prototype = p = new cjs.MovieClip();
	p.nominalBounds = new cjs.Rectangle(-67.1,-7,75.9,191.3);


	(lib.BeeAnim = function(mode,startPosition,loop) {
		this.initialize(mode,startPosition,loop,{start:0,stop:29,payoff_side:30,payoff_up:55,fly_away:78,go_away:119,go_away_bad:120},true);

		// timeline functions:
		this.frame_29 = function() {
			this.stop();
		}
		this.frame_30 = function() {
			if(this.first) whizz.playSound("bee");
		}
		this.frame_54 = function() {
			if(this.first) whizz.stopSound("bee");
		}
		this.frame_55 = function() {
			if(this.first) whizz.playSound("bee");
		}
		this.frame_77 = function() {
			this.stop();
			if(this.first) this.parent.parent.gameState = 'waiting';
			if(this.first) whizz.myManager.hideOK(false);
			if(this.first) whizz.stopSound("bee");
		}
		this.frame_78 = function() {
			if(this.first) whizz.playSound("bee");
		}
		this.frame_118 = function() {
			if(this.first)  this.parent.parent.clearGraphic();
			this.stop();
			if(this.first) whizz.stopSound("bee");
		}
		this.frame_119 = function() {
			this.stop();
			if(this.first) this.parent.parent.gameState = 'waiting_bad';
			if(this.first) whizz.myManager.hideOK(false);
		}
		this.frame_120 = function() {
			//this.parent.parent.forDraw.graphics.clear();
		}
		this.frame_159 = function() {
			if(this.first)  this.parent.parent.clearGraphic();
		}

		// actions tween:
		this.timeline.addTween(cjs.Tween.get(this).wait(29).call(this.frame_29).wait(1).call(this.frame_30).wait(24).call(this.frame_54).wait(1).call(this.frame_55).wait(22).call(this.frame_77).wait(1).call(this.frame_78).wait(40).call(this.frame_118).wait(1).call(this.frame_119).wait(1).call(this.frame_120).wait(39).call(this.frame_159));

		// bee
		var b = new cjs.SpriteSheetBuilder();
		b.addMovieClip(new lib.Bee(), null, whizz.scale);
		this.bee = new cjs.BitmapAnimation(b.build());
		this.bee.setTransform(0,210.6,1/whizz.scale,1/whizz.scale,0,0,0,8*whizz.scale,7.5*whizz.scale);

		this.bee.play();

		this.timeline.addTween(cjs.Tween.get(this.bee).to({x:-65.5,y:150.6},5).to({x:-2.6,y:124.6},4).to({x:-44.7,y:69.5},5).to({x:36.2,y:33.7},5).to({x:-28.5,y:5.5},5).to({x:0.3,y:-0.3},5).wait(1).to({x:3.3,y:-1.2},0).to({x:10.3},2).to({x:-3.6},2).to({x:3.2},2).to({x:10.2},2).to({x:-3.5},2).to({x:3.2},2).to({x:10.2},2).to({x:-3.6},2).to({x:3.3},2).to({x:10.2},2).to({x:-3.5},2).to({x:3.3},2).to({x:3.2},1).to({y:-8.2},2).to({y:5.5},2).to({y:-1.2},2).to({y:-8.2},2).to({y:5.5},2).to({y:-1.2},2).to({x:3.3,y:-8.2},2).to({x:3.2,y:5.5},2).to({y:-1.2},2).to({x:3.3,y:-8.2},2).to({x:3.2,y:-1.2},2).wait(1).to({x:203.2,y:188.6},20).to({x:543.1,y:138.6},20).to({x:3.2,y:-1.2},1).wait(1).to({x:16.8,y:-0.6},0).to({x:543.2,y:27.5},39).wait(1));

		// bg
		this.borderBox = new lib.border_box();
		this.borderBox.setTransform(0,0,1,1.002);

		this.timeline.addTween(cjs.Tween.get(this.borderBox).wait(29).to({_off:true},1).wait(130));

	}).prototype = p = new cjs.MovieClip();
	p.nominalBounds = new cjs.Rectangle(-12.4,-10.1,25,228.2);

})(lib_MA_GBR_0800KAx0100 = lib_MA_GBR_0800KAx0100||{}, images = images||{}, createjs = createjs||{}, whizz = whizz||{});
var lib_MA_GBR_0800KAx0100, images, createjs, whizz;
