
package com.italk2learn.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NextLesson", targetNamespace = "http://ITalk2Learn/ITalk2LearnWS")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NextLesson {


    /**
     * 
     * @param timestamp
     * @param prevStudentScore
     * @param prevLessonId
     * @param studentId
     * @param whizzLessonSuggestion
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://ITalk2Learn/ITalk2LearnWS/nextLesson")
    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "nextLesson", targetNamespace = "http://ITalk2Learn/ITalk2LearnWS", className = "italk2learn.italk2learnws.NextLesson_Type")
    @ResponseWrapper(localName = "nextLessonResponse", targetNamespace = "http://ITalk2Learn/ITalk2LearnWS", className = "italk2learn.italk2learnws.NextLessonResponse")
    public String nextLesson(
        @WebParam(name = "studentId", targetNamespace = "")
        int studentId,
        @WebParam(name = "prevStudentScore", targetNamespace = "")
        int prevStudentScore,
        @WebParam(name = "prevLessonId", targetNamespace = "")
        String prevLessonId,
        @WebParam(name = "timestamp", targetNamespace = "")
        XMLGregorianCalendar timestamp,
        @WebParam(name = "whizzLessonSuggestion", targetNamespace = "")
        String whizzLessonSuggestion);

}
